<?php
$this->headLink()
    ->appendStylesheet('/assets/dropzone/css/basic.css')
    ->appendStylesheet('/assets/dropzone/css/dropzone.css')
    ;

$this->inlineScript()
    ->appendFile('/assets/dropzone/dropzone.js')
    //->appendFile('/js/forms/project/setup.js')
;

$this->inlineScript()->captureStart();
echo <<<JS
<!-- 3 -->
Dropzone.options.myDropzone = {
    addRemoveLinks: true,
    init: function() {
        thisDropzone = this;
        
        <!-- 4 -->
        $.get('/client-{$project->getClient()->getClientId()}/project-{$project->getProjectId()}/filemanagerupload/', function(data) {
 
            <!-- 5 -->
            $.each(data, function(key,value){
                 
                var mockFile = { name: value.name, size: value.size };
                 
                thisDropzone.options.addedfile.call(thisDropzone, mockFile);
 
                //thisDropzone.options.thumbnail.call(thisDropzone, mockFile, "/client-{$project->getClient()->getClientId()}/project-{$project->getProjectId()}/filemanagerupload/"+value.name);
                thisDropzone.options.thumbnail.call(thisDropzone, mockFile, "/client-{$project->getClient()->getClientId()}/project-{$project->getProjectId()}/filemanagerretrieve/?file="+value.name);
                //thisDropzone.options.thumbnail.call(thisDropzone, mockFile, "/client-{$project->getClient()->getClientId()}/project-{$project->getProjectId()}/filemanagerretrieve/");
                //thisDropzone.options.thumbnail.call(thisDropzone, mockFile, "http://loc.8point3.co.uk/img/gallery/robot3.png");
                
                 
            });
             
        });
    }
};
                
$(function() {
    
});
JS;
$this->inlineScript()->captureEnd();

?><div class="row-fluid">
    <div class="span12">
        <!-- BEGIN BASIC PORTLET-->
        <div class="widget blue">
            <div class="widget-title">
                <h4><i class="icon-folder-open"></i> File Manager</h4>
                <span class="tools">
                    <a href="javascript:;" class="icon-chevron-down"></a>
                </span>
            </div>
            <div class="widget-body">
                <div class="row-fluid">
                    <div class="btn-toolbar">
                        <button id="btn1">button 1</button>
                        <button id="btn2">button 2</button>
                        <div class="btn-group">
                            <button data-toggle="dropdown" class="btn btn-large btn-primary dropdown-toggle"><i class="icon-bar-chart"></i> Accounts <span class="caret"></span></button>
                            <ul class="dropdown-menu">
                                <li><a href="#">Action</a></li>
                                <li><a href="#">Another action</a></li>
                                <li><a href="#">Something else here</a></li>
                                <li class="divider"></li>
                                <li><a href="#">Separated link</a></li>
                            </ul>
                        </div>
                        <div class="btn-group">
                            <button data-toggle="dropdown" class="btn btn-large btn-danger dropdown-toggle"><i class="icon-camera-retro"></i> Photos <span class="caret"></span></button>
                            <ul class="dropdown-menu">
                                <li><a href="#">Action</a></li>
                                <li><a href="#">Another action</a></li>
                                <li><a href="#">Something else here</a></li>
                                <li class="divider"></li>
                                <li><a href="#">Separated link</a></li>
                            </ul>
                        </div>
                        <div class="btn-group">
                            <button data-toggle="dropdown" class="btn btn-large btn-warning dropdown-toggle"><i class="icon-list-ul"></i> Quotes <span class="caret"></span></button>
                            <ul class="dropdown-menu">
                                <li><a href="#">Action</a></li>
                                <li><a href="#">Another action</a></li>
                                <li><a href="#">Something else here</a></li>
                                <li class="divider"></li>
                                <li><a href="#">Separated link</a></li>
                            </ul>
                        </div>
                        <div class="btn-group">
                            <button data-toggle="dropdown" class="btn btn-large btn-success dropdown-toggle"><i class="icon-building"></i> Survey <span class="caret"></span></button>
                            <ul class="dropdown-menu">
                                <li><a href="#">Action</a></li>
                                <li><a href="#">Another action</a></li>
                                <li><a href="#">Something else here</a></li>
                                <li class="divider"></li>
                                <li><a href="#">Separated link</a></li>
                            </ul>
                        </div>
                        <div class="btn-group">
                            <button data-toggle="dropdown" class="btn btn-large btn-info dropdown-toggle"><i class="icon-wrench"></i> Install <span class="caret"></span></button>
                            <ul class="dropdown-menu">
                                <li><a href="#">Action</a></li>
                                <li><a href="#">Another action</a></li>
                                <li><a href="#">Something else here</a></li>
                                <li class="divider"></li>
                                <li><a href="#">Separated link</a></li>
                            </ul>
                        </div>
                        <div class="btn-group">
                            <button data-toggle="dropdown" class="btn btn-large btn-inverse dropdown-toggle"><i class="icon-folder-close-alt"></i> Other <span class="caret"></span></button>
                            <ul class="dropdown-menu">
                                <li><a href="#">Action</a></li>
                                <li><a href="#">Another action</a></li>
                                <li><a href="#">Something else here</a></li>
                                <li class="divider"></li>
                                <li><a href="#">Separated link</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <hr>
                <form action="/client-<?php echo $project->getClient()->getClientId(); ?>/project-<?php echo $project->getProjectId(); ?>/filemanagerupload/" class="dropzone" id="my-dropzone"></form>
                <!--<form action="/client-<?php echo $project->getClient()->getClientId(); ?>/project-<?php echo $project->getProjectId(); ?>/filemanagerupload/" class="dropzone" id="my-awesome-dropzone"></form><!-- -->

            </div>
        </div>
    </div>
</div>
