<?php 
$this->headLink()
    ->appendStylesheet('/assets/uniform/css/uniform.default.css')
    ->appendStylesheet('/assets/data-tables/DT_bootstrap.css');

$this->inlineScript()
    ->appendFile('/assets/uniform/jquery.uniform.min.js')
    ->appendFile('/js/jquery.blockui.js')
    ->appendFile('/assets/data-tables/jquery.dataTables.js')
    ->appendFile('/assets/data-tables/DT_bootstrap.js')
    //->appendFile('/js/dynamic-table/project.js')
    ;

$closed = $project->getCancelled();
$job = false;


$mcd = $project->getMCD();

$prjVal = 0;
$prjMargin = 0;
$prds = 0;
$tmpCpuTotal = 0;
$tmpPpuTotal = 0;
if (!empty($system)) {
    foreach ($system as $sys) {
        if (empty($sys['service'])) {
            $prds+=$sys['quantity'];
            $priceMCD = round($sys['price'] * (1-$mcd), 2);
            $prjVal+=$priceMCD ;
            $tmpCpuTotal+=$sys['cost'];
            $tmpPpuTotal+=$priceMCD;
            if ($project->getIbp()) {
                $prjVal+=round($priceMCD * 0.018, 2);
            }
        } else {
            /*
            // Note: we have taken this out as we will get margin from product items only
            $tmpCpuTotal+=$sys['cost'];
            $tmpPpuTotal+=$sys['price'];/**/
            
            $prjVal+=$sys['price'];
        }
    }
}
?>
<?php 
$notes = $project->getNotes();
if (!empty($notes)) {
    $notesArr  = json_decode($notes);
    if (!empty($notesArr)) {
?>
<div class="row-fluid">
    <div class="span12">
        <div class="alert alert-info relative" id="project-notes">
            <div id="noteDeleteLoader" class="loader"></div>
            <button class="close btn-add-note" >+</button>
<?php
        $cnt = 0;
        foreach ($notesArr as $idx=>$note) {
            $cnt++;
            echo "<div class=\"note\"><strong>Note:</strong> {$note} <a data-index=\"{$idx}\" href=\"javascript:\" class=\"delete-note\"><i class=\"icon-remove\"></i></a></div>";
        }
?>
        </div>
    </div>
</div>
<?php
    }
}
?>
<?php
if ($project->getTest()) {
  ?>
<div class="row-fluid">
    <div class="span12">
        <div class="alert alert-error">
            <strong>Important Notice:</strong> this project is in test mode and will not show up on reporting. Material generated from this project should not be presented to the client.
        </div>
    </div>
</div>
<?php
}
?>
<div class="row-fluid">
    <div class="span12">
        <div class="row-fluid">
            <a class="icon-btn span2" href="/client-<?php echo $project->getClient()->getClientId(); ?>/project-<?php echo $project->getProjectId(); ?>/setup/">
                <i class="icon-gears"></i>
                <div>Configuration  </div>
                
            </a>
            <a class="icon-btn span2" href="/client-<?php echo $project->getClient()->getClientId(); ?>/project-<?php echo $project->getProjectId(); ?>/system/">
                <i class="icon-sitemap"></i>
                <div>System Setup</div>
                <span class="badge badge-info"><?php echo $prds; ?></span>
            </a>
            <a class="icon-btn span2" href="/client-<?php echo $project->getClient()->getClientId(); ?>/project-<?php echo $project->getProjectId(); ?>/model/">
                <i class="icon-bar-chart"></i>
                <div>Model</div>
            </a>
            <a class="icon-btn span2" href="/client-<?php echo $project->getClient()->getClientId(); ?>/project-<?php echo $project->getProjectId(); ?>/collaborators/">
                <i class="icon-group"></i>
                <div>Collaborators  </div>
                <span class="badge badge-important"><?php echo count($project->getCollaborators()); ?></span>
            </a>
            <a class="icon-btn span2" href="/client-<?php echo $project->getClient()->getClientId(); ?>/project-<?php echo $project->getProjectId(); ?>/bluesheet/">
                <i class="icon-file-text-alt"></i>
                <div>Blue Sheet</div>
            </a>
            <a class="icon-btn span2 btn-add-note" href="#">
                <i class="icon-calendar"></i>
                <div>Notes</div>
                <span class="badge badge-success">+</span>
            </a>
        </div>
    </div>
</div>
<div class="row-fluid">
    <div class="blog span12">
        <div class="span2 <?php echo $closed?'red':(($project->getRating()==3)?'green':(($project->getRating()==2)?'orange':(($project->getRating()==1)?'red':'green'))); ?>">
            <a href="javascript:;" class="blog-features date active">
                <i class=" icon-<?php echo $closed?'ban-circle':(($project->getRating()>0)?'flag':'question-sign'); ?>"></i>
                <p class="month"><?php echo $closed?'lost':(($project->getRating()==1)?'Red Rated':(($project->getRating()==2)?'Amber Rated':(($project->getRating()==3)?'Green Rated':'Un-rated'))); ?></p>
            </a>
            <a href="/client-<?php echo $project->getClient()->getClientId(); ?>/project-<?php echo $project->getProjectId(); ?>/system/" class="blog-features comments">
                <i class=" icon-gear"></i>
                <p class="info"><?php 
                    
                    echo $prds; 
                    ?> Products</p>
            </a>
            <a href="javascript:;" class="blog-features comments">
                <i class=" icon-file-text"></i>
                <p class="info"><?php echo $proposals; ?> Proposals</p>
            </a>
            <a href="javascript:;" class="blog-features comments">
                <i class=" icon-info"></i>
                <p class="info"><?php echo str_pad($project->getClient()->getClientId(), 5, "0", STR_PAD_LEFT),'-',str_pad($project->getProjectId(), 5, "0", STR_PAD_LEFT) ?></p>
            </a>
        </div>
        <div class="span10">
            <h2>
                <?php echo $project->getName(); ?>
            </h2>
            <p>
                OWNER <a href="javascript:;" class="author"><?php echo strtoupper($project->getClient()->getUser()->getHandle()); ?></a> |  
                CREATED: <?php echo $project->getcreated()->format('d/m/Y H:i'); ?> | 
                REFERENCE: <?php echo str_pad($project->getClient()->getClientId(), 5, "0", STR_PAD_LEFT),'-',str_pad($project->getProjectId(), 5, "0", STR_PAD_LEFT) ?>
            </p>
            <h5>Weighting<span class="pull-right"><?php echo $project->getWeighting(); ?>%</span></h5>
            <div id="slider-range-min" class="slider"></div>
            <div class="progress progress-striped progress-<?php
                if ($project->getWeighting()<10) {
                    echo 'danger';
                } elseif ($project->getWeighting()<30) {
                    echo 'warning';
                } elseif ($project->getWeighting()<50) {
                    echo 'info';
                } elseif ($project->getWeighting()<80) {
                    echo 'striped';
                } else {
                    echo 'success';
                }

            ?>">
                <div style="width: <?php echo $project->getWeighting(); ?>%;" class="bar"></div>
            </div>
            <p> Below are displayed the details of the project including information about the LED 
                systems that are planned and a file management section in which project files can be managed. </p>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th colspan="2">
                            Project Information
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td style="width: 120px">
                            Project States
                        </td>
                        <td>
                            <?php 
                                $labelTypes = array(
                                    'important',
                                    'info',
                                    'success',
                                    'warning',
                                    'default',
                                );
                                $labelIdx = 0;
                                foreach ($project->getStates() as $state) {
                                    echo '<span class="label label-'.$labelTypes[$labelIdx].' label-mini">'.ucwords($state->getName()).'</span>&nbsp;';
                                    $labelIdx++;
                                    if ($labelIdx>(count($labelTypes)-1)) {
                                        $labelIdx = 0;
                                    }
                                }
                             ?>
                            <a href="/client-<?php echo $project->getClient()->getClientId(); ?>/project-<?php echo $project->getProjectId(); ?>/setup/" class="" style="float: right">Modify Project Settings&nbsp;&nbsp;<i class=" icon-cog"></i></a>
                        </td>
                    </tr>
                    <?php
                        $contactList = array();
                        if (!count($contacts)) {
                            $contactList[] = 'No contacts assigned to project';
                        } else {
                            foreach ($contacts as $contact) {
                                $contactList[] = $contact->getTitle()->getDisplay().' '.$contact->getForename().' '.$contact->getSurname();
                            }
                        }
                    
                    ?>
                    <tr>
                        <td rowspan="<?php echo count($contactList); ?>">
                            Registered Contact
                        </td>
                        <td>
                            <?php 
                            echo array_shift($contactList);
                            ?>&nbsp;
                            <a href="javascript:" id="addmeeting" class=" " style="float: right">Add Meeting To Calendar&nbsp;&nbsp;<i class="icon-calendar"></i></a>
                        </td>
                    </tr>
                    <?php
                        if (!empty($contactList)) {
                            echo '<tr><td>'.implode('</td></tr><tr><td>', $contactList).'</td></tr>';
                        }
                    ?>
                    <tr>
                        <td >
                            Project Value
                        </td>
                        <td>&#163;
                            <?php 
                                echo number_format($prjVal, 2);
                             ?>
                        </td>
                    </tr>
                    <tr>
                        <td >
                            Project Margin
                        </td>
                        <td>
                            <?php 
                                if (($tmpPpuTotal>0) && ($tmpCpuTotal>0)) {
                                    $prjMargin = (($tmpPpuTotal - $tmpCpuTotal)/$tmpPpuTotal)*100;
                                } 
                                echo number_format($prjMargin, 2);
                             ?>%
                             <span class="badge badge-<?php echo (($prjMargin>=35)?'success':(($prjMargin>=20)?'warning':'important')); 
                             ?> pull-right"><i class="icon-<?php echo (($prjMargin>=35)?'ok':(($prjMargin>=20)?'ok':'remove')); 
                             ?>"></i> <?php echo (($prjMargin>=35)?'High':(($prjMargin>=20)?'Medium':'Low')); 
                             ?> Margin</span>
                        </td>
                    </tr>
                    <tr>
                        <td>Lighting Design</td>
                        <td><?php
                            /*if (empty($prds)) {
                                echo 'No products added to project - lighting design unavailable on empty systems';
                            } else { /**/
                                if ($ldMode==1) {
                                    echo '<span class="text-info">Lighting design has been requested</span>';
                                    if ($task instanceof Task\Entity\Task) echo '<a class="pull-right" href="/task-'.$task->getTaskId().'/">Open Task <i class="icon-double-angle-right"></i></a>';
                                } elseif ($ldMode==2) {
                                    echo '<span class="text-success">Lighting design has been completed</span>';
                                    if ($task instanceof Task\Entity\Task) echo '<a class="pull-right" href="/task-'.$task->getTaskId().'/">Open Task <i class="icon-double-angle-right"></i></a>';
                                } elseif ($ldMode==600) {
                                    echo '<span class="text-error">Lighting design team unavailable to undertake additional tasks</span>';
                                } else {
                                    echo '<span class="text-error">Lighting design has not been undertaken for this project</span> <a href="#modalAddTask" data-original-title="" role="button" data-toggle="modal" class="pull-right">Request Lighting Design&nbsp;&nbsp;<i class="icon-double-angle-right"></i></a>';
                                }
                            //}
                            ?></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="row-fluid">
    <div class="span12">
        <!-- BEGIN BASIC PORTLET-->
        <div class="widget orange">
            <div class="widget-title">
                <h4><i class="icon-cogs"></i> System Overview</h4>
            <span class="tools">
                <a href="javascript:;" class="icon-chevron-down"></a>
            </span>
            </div>
            <div class="widget-body">
                <table class="table table-striped table-bordered table-advance table-hover" id="products_tbl">
                    <thead>
                        <tr>
                            <th ><i class="icon-cog"></i> Product Name</th>
                            <th class="hidden-phone"> Product Type</th>
                            <th class="hidden-phone" style="width: 40px"> ECA</th>
                            <th class="hidden-phone"> PPU</th>
                            <th style="width: 110px"> Quantity</th>
                            <th style="width: 140px"> Price (inc MCD)</th>
                        </tr>
                    </thead>
                    <tbody>
<?php
    $totalInstallation = 0;
    $totalDelivery = 0;
    $totalAccess = 0;
    $totalOther = 0;
    $totalIbp = 0;
    
    $totalPriceMCD = 0;
    $totalQuantity = 0;
    if (!empty($system)) {
        $mcd = $project->getMCD();
        foreach ($system as $product) {
            if (!$product['service']) {
                $priceMCD = round($product['price'] * (1-$mcd), 2);
                $totalPriceMCD+=$priceMCD;
                $totalQuantity+=$product['quantity'];
                if ($project->getIbp()) {
                    $totalIbp+=round($priceMCD * 0.018, 2);
                }

                echo '<tr>
                        <td>'.$product['model'].'</td>
                        <td>'.$product['productType'].'</td>
                        <td>'.(($product['eca']==1)?'<span class="label label-success"><i class=" icon-ok"></i></span>':'<span class="label label-important"><i class=" icon-ban-circle"></i></span>').'</td>
                        <td class="row-right">'.$product['ppu'].'</td>
                        <td class="row-right">'.$product['quantity'].'</td>
                        <td class="row-right">'.number_format($priceMCD,2).'</td>
                    </tr>';
            } else {
                $price = $product['price'];
                if($product['typeId'] == 100) {
                    $totalInstallation+=$price; // type 100 is an installation product
                } elseif($product['typeId'] == 101) {
                    $totalDelivery+=$price; // type 100 is an installation product
                } elseif($product['typeId'] == 102) {
                    $totalAccess+=$price; // type 100 is an installation product
                } else {
                    $totalOther+=$price; // type 100 is an installation product
                }
                
            }
        }
        
        echo '<tr>
            <td colspan="6">&nbsp;</td>
        </tr>';
        
        echo '<tr>
                <th colspan="5">Total Product Cost</th>
                <td class="row-right">'.number_format($totalPriceMCD,2).'</td>
            </tr>';
        
        if (!empty($totalInstallation)) {
            echo '<tr>
                <th colspan="5">Installation Cost</th>
                <td class="row-right">'.number_format($totalInstallation,2).'</td>
            </tr>';

        }
        
        if (!empty($totalDelivery)) {
            echo '<tr>
                <th colspan="5">Delivery Cost</th>
                <td class="row-right">'.number_format($totalDelivery,2).'</td>
            </tr>';

        }
        
        if (!empty($totalAccess)) {
            echo '<tr>
                <th colspan="5">Access Cost</th>
                <td class="row-right">'.number_format($totalAccess,2).'</td>
            </tr>';

        }
        
        if (!empty($totalOther)) {
            echo '<tr>
                <th colspan="5">Other Costs</th>
                <td class="row-right">'.number_format($totalOther,2).'</td>
            </tr>';

        }
        
        if (!empty($totalIbp)) {
            echo '<tr>
                <th colspan="5">Insurance Backed Premium Cost</th>
                <td class="row-right">'.number_format($totalIbp,2).'</td>
            </tr>';

        }
        
    }/**/
?>
                    </tbody>
                    <tfoot>
                        <tr>
                            <th colspan="4">TOTAL</th>
                            <td class="row-right"><?php echo $totalQuantity; ?></td>
                            <th class="row-right">&#163;<?php echo number_format($totalPriceMCD + $totalInstallation + $totalDelivery + $totalAccess + $totalOther + $totalIbp,2); ?></th>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
        <!-- END BASIC PORTLET-->
    </div>
</div>
<div class="row-fluid">
     <div class="span6">
         <!-- BEGIN NOTIFICATIONS PORTLET-->
         <div class="widget blue">
             <div class="widget-title">
                 <h4><i class="icon-bell"></i> Project Activity </h4>
               <span class="tools">
                   <a href="javascript:;" class="icon-chevron-down"></a>
                   <a href="javascript:;" class="icon-remove"></a>
               </span>
             </div>
             <div class="widget-body">
                 <ul class="item-list scroller padding"  style="overflow: hidden; width: auto; height: 320px;" data-always-visible="1">
                     <?php
                        if (!empty($audit)) {
                            $i=0;
                            foreach ($audit as $aItem) {
                                $tm = (time()-$aItem['created']->getTimestamp());
                                $days = floor(($tm/(60*60*24)));
                                $hours = ($tm - ($days*60*60*24))/(60*60);
                                $when= (($tm/60)<2)
                                        ?'Just now'
                                        :(
                                            (($tm/60)<60)
                                            ?ceil($tm/60).' mins ago'
                                            :(
                                                ($days<1)
                                                ?floor($hours).' hour'.(($hours>=2)?'s':'').' ago'
                                                :$days.' day'.(($days>=2)?'s':'').' '.(
                                                    ($hours>0)
                                                    ?floor($hours).' hour'.(($hours>=2)?'s':'').' '
                                                    :''
                                                ).'ago'    
                                            )
                                        );
                                
                                $tooltip_data = '';
                                $tooltip = '';
                                $url = '';
                                
                                $aData = json_decode($aItem['data'], true);
                                
                                if (!empty($aItem['dName'])) {
                                    $tooltip_data.=$aItem['dName'];
                                    if (!empty($aItem['projectId'])) {
                                        $url = '/client-'.$aItem['clientId'].'/project-'.$aItem['projectId'].'/document/index/';
                                    }
                                } elseif (!empty($aItem['model'])) {
                                    $tooltip_data.=trim($aItem['model']);
                                    $url = '/client-'.$aItem['clientId'].'/project-'.$aItem['projectId'].'/space-'.$aItem['spaceId'].'/';
                                } elseif (!empty($aItem['sName'])) {
                                    $tooltip_data.=$aItem['sName'];
                                    $url = '/client-'.$aItem['clientId'].'/project-'.$aItem['projectId'].'/space-'.$aItem['spaceId'].'/';
                                } 
                                
                                if (!empty($tooltip_data)) {
                                    $tooltip = 'data-trigger="hover" data-placement="right" data-original-title="'.$tooltip_data.'"';
                                }
                                
                                
                                
                                //break;
                                echo '<li>
                                    <span '.$tooltip.' class="audit '.(empty($tooltip)?'':'tooltips ').'label label-'.(empty($aItem['box'])?'success':$aItem['box']).'" '
                                        . (!empty($url)?'data-url="'.$url.'" data-link="true"':'')
                                    . '><i '
                                        . 'class="icon-'.(empty($aItem['icon'])?'bell':$aItem['icon']).'"></i></span>
                                    <span class="link">'.
                                        $aItem['atName'].
                                    '</span>
                                    <div class="pull-right">
                                        <span class="small italic ">'.$when.'</span>
                                    </div>
                                </li>';
                            } 
                        } else {
                             echo '<li>
                                    <span class="label label-default"><i class="icon-bell"></i></span>
                                    <span class="link">No Activity Information Found</span>
                                    <div class="pull-right">
                                        <span class="small italic ">&nbsp;</span>
                                    </div>
                                </li>';
                        }
                    ?>  
                 </ul>
                 <div class="space10"></div>
                 <a href="/client-<?php echo $project->getClient()->getClientId(); ?>/project-<?php echo $project->getProjectId(); ?>/audit/" class="pull-right">View detailed project audit log</a>
                 <div class="clearfix no-top-space no-bottom-space"></div>
             </div>
         </div>
         <!-- END NOTIFICATIONS PORTLET-->
     </div>
     <div class="span6">
         <!-- BEGIN CHAT PORTLET-->
         <?php echo $this->partial('partial/panels/activity.phtml'); ?>
         <!-- END CHAT PORTLET-->
     </div>
 </div>
<?php echo $this->partial('partial/project/notes.phtml'); ?>
<?php if (empty($ldMode)) {
    echo $this->partial('partial/project/task/lightingdesign.phtml');
}

    echo $this->partial('partial/calendar/project.phtml');
?>
