<?php 
$this->headLink()
    ->appendStylesheet('/assets/bootstrap-toggle-buttons/static/stylesheets/bootstrap-toggle-buttons.css')
    ;

$this->inlineScript()
    ->appendFile('/assets/bootstrap-toggle-buttons/static/js/jquery.toggle.buttons.js')
    ->appendFile('/js/forms/project/setup.js')
/**/;


$this->inlineScript()->captureStart();
echo <<<JS
    $(function(){
        $("#slider-range-min").slider({
            range: "min",
            value: {$project->getWeighting()},
            min: 0,
            max: 100,
            slide: function (event, ui) {
                $("#slider-range-min-amount").text('Current Weighting: ' + ui.value + "%");
            },
            change: function (event, ui) {
                $('input[name=weighting]').val(ui.value);
            }
        });

        $("#slider-range-min-amount").text('Current Weighting: '+$("#slider-range-min").slider("value")+'%');
        
            /**/
    });

JS;
$this->inlineScript()->captureEnd();





$form = $this->form;
$form->setAttribute('class', 'form-horizontal');
$form->prepare();


?>
<?php echo $this->form()->openTag($form); ?>
<div class="row-fluid">
    <div class="span12">
        <!-- BEGIN SAMPLE FORMPORTLET-->
        <div id="msgs"></div>
        <div class="widget blue relative">
            <div id="setupLoader2" class="loader"></div>
            <div class="widget-title">
                <h4><i class="icon-cog"></i> Project Weighting </h4>
                <span class="tools">
                <a href="javascript:;" class="icon-chevron-down"></a>
                <a href="javascript:;" class="icon-remove"></a>
                </span>
            </div>
            <div class="widget-body">
                <!-- BEGIN FORM-->
                <div class="control-group">
                        <div class="widget-body">
                            <div class="sliders">
                                 Select the weighting that best reflects the progress of the project.<br />&nbsp;<?php echo $this->formElement($form->get('weighting'));  ?>
                                <div id="slider-range-min" class="slider"></div>
                                <div class="slider-info">
                                    <span class="slider-info" id="slider-range-min-amount"></span>
                                </div>
                            </div>
                        </div>
                </div>
                <!-- END FORM-->
            </div>
        </div>
        <!-- END SAMPLE FORM PORTLET-->
    </div>
</div>
<div class="row-fluid">
    <div class="span12">
        <!-- BEGIN SAMPLE FORMPORTLET-->
        <div class="widget green relative">
            <div id="setupLoader" class="loader"></div>
            <div class="widget-title">
                <h4><i class="icon-cog"></i> Project Configuration </h4>
                <span class="tools">
                <a href="javascript:;" class="icon-chevron-down"></a>
                <a href="javascript:;" class="icon-remove"></a>
                </span>
            </div>
            <div class="widget-body">
                <!-- BEGIN FORM-->
                <div class="control-group">
                    <label class="control-label">Name</label>
                    <div class="controls">
                        <?php echo $this->formElement($form->get('name'));  ?>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">Mode</label>
                    <div class="controls">
                        <div id="text-toggle-button">
                            <?php echo $this->formElement($form->get('test'));  ?>
                        </div>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">Sector</label>
                    <div class="controls">
                        <?php echo $this->formElement($form->get('sector'));  ?>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">Type</label>
                    <div class="controls">
                        <?php echo $this->formElement($form->get('type'));  ?>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">Status</label>
                    <div class="controls">
                        <?php echo $this->formElement($form->get('status'));  ?>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">Finance Provider</label>
                    <div class="controls">
                        <?php echo $this->formElement($form->get('financeProvider'));  ?>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">Finance Option</label>
                    <div class="controls">
                        <?php echo $this->formElement($form->get('financeYears'));  ?>
                    </div>
                </div>

                <div class="control-group">
                    <label class="control-label">Carbon Factor</label>
                    <div class="controls">
                        <?php echo $this->formElement($form->get('co2'));  ?>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">Fuel Tariff</label>
                    <div class="controls">
                        <div class="input-prepend input-append">
                        <?php echo $this->formElement($form->get('fuelTariff'));  ?><span class="add-on">pence per unit</span>
                        </div>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">RPI</label>
                    <div class="controls">
                        <?php echo $this->formElement($form->get('rpi'));  ?>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">EPI</label>
                    <div class="controls">
                        <?php echo $this->formElement($form->get('epi'));  ?>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">MCD</label>
                    <div class="controls">
                        <?php echo $this->formElement($form->get('mcd'));  ?>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">ECA Factor</label>
                    <div class="controls">
                        <?php echo $this->formElement($form->get('eca'));  ?>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">Carbon Allowance</label>
                    <div class="controls">
                        <?php echo $this->formElement($form->get('carbon'));  ?>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">Default Model</label>
                    <div class="controls">
                        <?php echo $this->formElement($form->get('model'));  ?>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">Warranty Type</label>
                    <div class="controls">
                        <?php echo $this->formElement($form->get('ibp'));  ?>
                    </div>
                </div>
                 <div class="form-actions">
                     <button name="submit" type="submit" class="btn btn-success">Save Changes</button>
                </div>
                <!-- END FORM-->
            </div>
        </div>
        <!-- END SAMPLE FORM PORTLET-->
    </div>
</div>
<?php echo $this->form()->closeTag($form); ?>
            
