<ul class="sidebar-menu">
<?php

    function addSubMenu($page, &$html) {
        $active = false;
        if ($page->hasPages()) {
            $html='<ul class="sub">';
            foreach($page->getPages() as $child) {
                if ($child->isActive()) $active=true;
                $html.='<li class="'.($child->isActive()?'active':'').'"><a class="" href="'.$child->getHref().'">'.(!empty($child->mlabel)?$child->mlabel:$child->getLabel()).'</a></li>';
            }
            $html.='</ul>';
        }
        
        return $active;
    }

    function addMenu($page) {
        if (!empty($page->skip)) {
            foreach($page->getPages() as $page2) {
                addMenu($page2);
            }
        } else {
            $hasChildren = $page->hasPages();
            $subMenu = '';
            $subActive = addSubMenu($page, $subMenu);
            echo '<li class="sub-menu'.(($page->isActive()||$subActive)?' active':'').'">';
            echo '<a class="" '.(!$hasChildren?'href="'.$page->getHref():'').'">'.
                (!empty($page->ico)?'<i class="'.$page->ico.'"></i>':'').'
                      <span>'.(!empty($page->mlabel)?$page->mlabel:$page->getLabel()).'</span>
                  </a>';
            echo $subMenu;
            echo '</li>';
        }
    }
     // iterate through the pages
    foreach ($this->container as $page) {
        addMenu ($page);
    }     
?>
</ul>