<?php

namespace DoctrineORMModule\Proxy\__CG__\Client\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Client extends \Client\Entity\Client implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'name', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'regno', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'url', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'fund', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'created', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'notes', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'user', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'source', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'financeStatus', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'paymentTerms', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'collaborators', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'clientId', 'inputFilter');
        }

        return array('__isInitialized__', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'name', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'regno', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'url', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'fund', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'created', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'notes', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'user', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'source', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'financeStatus', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'paymentTerms', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'collaborators', '' . "\0" . 'Client\\Entity\\Client' . "\0" . 'clientId', 'inputFilter');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Client $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getPaymentTerms()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentTerms', array());

        return parent::getPaymentTerms();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaymentTerms($paymentTerms)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentTerms', array($paymentTerms));

        return parent::setPaymentTerms($paymentTerms);
    }

    /**
     * {@inheritDoc}
     */
    public function getCollaborators()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCollaborators', array());

        return parent::getCollaborators();
    }

    /**
     * {@inheritDoc}
     */
    public function setCollaborators($collaborators)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCollaborators', array($collaborators));

        return parent::setCollaborators($collaborators);
    }

    /**
     * {@inheritDoc}
     */
    public function addCollaborators(\Doctrine\Common\Collections\Collection $collaborators)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCollaborators', array($collaborators));

        return parent::addCollaborators($collaborators);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCollaborators(\Doctrine\Common\Collections\Collection $collaborators)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCollaborators', array($collaborators));

        return parent::removeCollaborators($collaborators);
    }

    /**
     * {@inheritDoc}
     */
    public function setClientId($clientId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClientId', array($clientId));

        return parent::setClientId($clientId);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function getRegno()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegno', array());

        return parent::getRegno();
    }

    /**
     * {@inheritDoc}
     */
    public function getUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrl', array());

        return parent::getUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function getFund()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFund', array());

        return parent::getFund();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreated', array());

        return parent::getCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', array());

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function getSource()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSource', array());

        return parent::getSource();
    }

    /**
     * {@inheritDoc}
     */
    public function getFinanceStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFinanceStatus', array());

        return parent::getFinanceStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function getClientId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getClientId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientId', array());

        return parent::getClientId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function setRegno($regno)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegno', array($regno));

        return parent::setRegno($regno);
    }

    /**
     * {@inheritDoc}
     */
    public function setUrl($url)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUrl', array($url));

        return parent::setUrl($url);
    }

    /**
     * {@inheritDoc}
     */
    public function setFund($fund)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFund', array($fund));

        return parent::setFund($fund);
    }

    /**
     * {@inheritDoc}
     */
    public function setCreated(\DateTime $created)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreated', array($created));

        return parent::setCreated($created);
    }

    /**
     * {@inheritDoc}
     */
    public function setUser($user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', array($user));

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function setSource($source)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSource', array($source));

        return parent::setSource($source);
    }

    /**
     * {@inheritDoc}
     */
    public function setFinanceStatus($financeStatus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFinanceStatus', array($financeStatus));

        return parent::setFinanceStatus($financeStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getNotes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNotes', array());

        return parent::getNotes();
    }

    /**
     * {@inheritDoc}
     */
    public function setNotes($notes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNotes', array($notes));

        return parent::setNotes($notes);
    }

    /**
     * {@inheritDoc}
     */
    public function populate($data = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'populate', array($data));

        return parent::populate($data);
    }

    /**
     * {@inheritDoc}
     */
    public function getArrayCopy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArrayCopy', array());

        return parent::getArrayCopy();
    }

    /**
     * {@inheritDoc}
     */
    public function setInputFilter(\Zend\InputFilter\InputFilterInterface $inputFilter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInputFilter', array($inputFilter));

        return parent::setInputFilter($inputFilter);
    }

    /**
     * {@inheritDoc}
     */
    public function getInputFilter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInputFilter', array());

        return parent::getInputFilter();
    }

}
