<?php

namespace DoctrineORMModule\Proxy\__CG__\Contact\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Address extends \Contact\Entity\Address implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Contact\\Entity\\Address' . "\0" . 'label', '' . "\0" . 'Contact\\Entity\\Address' . "\0" . 'line1', '' . "\0" . 'Contact\\Entity\\Address' . "\0" . 'line2', '' . "\0" . 'Contact\\Entity\\Address' . "\0" . 'line3', '' . "\0" . 'Contact\\Entity\\Address' . "\0" . 'line4', '' . "\0" . 'Contact\\Entity\\Address' . "\0" . 'line5', '' . "\0" . 'Contact\\Entity\\Address' . "\0" . 'postcode', '' . "\0" . 'Contact\\Entity\\Address' . "\0" . 'lat', '' . "\0" . 'Contact\\Entity\\Address' . "\0" . 'lng', '' . "\0" . 'Contact\\Entity\\Address' . "\0" . 'created', '' . "\0" . 'Contact\\Entity\\Address' . "\0" . 'client', '' . "\0" . 'Contact\\Entity\\Address' . "\0" . 'addressId', 'inputFilter');
        }

        return array('__isInitialized__', '' . "\0" . 'Contact\\Entity\\Address' . "\0" . 'label', '' . "\0" . 'Contact\\Entity\\Address' . "\0" . 'line1', '' . "\0" . 'Contact\\Entity\\Address' . "\0" . 'line2', '' . "\0" . 'Contact\\Entity\\Address' . "\0" . 'line3', '' . "\0" . 'Contact\\Entity\\Address' . "\0" . 'line4', '' . "\0" . 'Contact\\Entity\\Address' . "\0" . 'line5', '' . "\0" . 'Contact\\Entity\\Address' . "\0" . 'postcode', '' . "\0" . 'Contact\\Entity\\Address' . "\0" . 'lat', '' . "\0" . 'Contact\\Entity\\Address' . "\0" . 'lng', '' . "\0" . 'Contact\\Entity\\Address' . "\0" . 'created', '' . "\0" . 'Contact\\Entity\\Address' . "\0" . 'client', '' . "\0" . 'Contact\\Entity\\Address' . "\0" . 'addressId', 'inputFilter');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Address $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getLabel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLabel', array());

        return parent::getLabel();
    }

    /**
     * {@inheritDoc}
     */
    public function getLine1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLine1', array());

        return parent::getLine1();
    }

    /**
     * {@inheritDoc}
     */
    public function getLine2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLine2', array());

        return parent::getLine2();
    }

    /**
     * {@inheritDoc}
     */
    public function getLine3()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLine3', array());

        return parent::getLine3();
    }

    /**
     * {@inheritDoc}
     */
    public function getLine4()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLine4', array());

        return parent::getLine4();
    }

    /**
     * {@inheritDoc}
     */
    public function getLine5()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLine5', array());

        return parent::getLine5();
    }

    /**
     * {@inheritDoc}
     */
    public function getPostcode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostcode', array());

        return parent::getPostcode();
    }

    /**
     * {@inheritDoc}
     */
    public function getLat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLat', array());

        return parent::getLat();
    }

    /**
     * {@inheritDoc}
     */
    public function getLng()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLng', array());

        return parent::getLng();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreated', array());

        return parent::getCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function getAddressId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getAddressId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddressId', array());

        return parent::getAddressId();
    }

    /**
     * {@inheritDoc}
     */
    public function setLabel($label)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLabel', array($label));

        return parent::setLabel($label);
    }

    /**
     * {@inheritDoc}
     */
    public function getClient()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClient', array());

        return parent::getClient();
    }

    /**
     * {@inheritDoc}
     */
    public function setLine1($line1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLine1', array($line1));

        return parent::setLine1($line1);
    }

    /**
     * {@inheritDoc}
     */
    public function setLine2($line2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLine2', array($line2));

        return parent::setLine2($line2);
    }

    /**
     * {@inheritDoc}
     */
    public function setLine3($line3)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLine3', array($line3));

        return parent::setLine3($line3);
    }

    /**
     * {@inheritDoc}
     */
    public function setLine4($line4)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLine4', array($line4));

        return parent::setLine4($line4);
    }

    /**
     * {@inheritDoc}
     */
    public function setLine5($line5)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLine5', array($line5));

        return parent::setLine5($line5);
    }

    /**
     * {@inheritDoc}
     */
    public function setPostcode($postcode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostcode', array($postcode));

        return parent::setPostcode($postcode);
    }

    /**
     * {@inheritDoc}
     */
    public function setLat($lat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLat', array($lat));

        return parent::setLat($lat);
    }

    /**
     * {@inheritDoc}
     */
    public function setLng($lng)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLng', array($lng));

        return parent::setLng($lng);
    }

    /**
     * {@inheritDoc}
     */
    public function setCreated(\DateTime $created)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreated', array($created));

        return parent::setCreated($created);
    }

    /**
     * {@inheritDoc}
     */
    public function setClient($client)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClient', array($client));

        return parent::setClient($client);
    }

    /**
     * {@inheritDoc}
     */
    public function setAddressId($addressId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddressId', array($addressId));

        return parent::setAddressId($addressId);
    }

    /**
     * {@inheritDoc}
     */
    public function assemble($sep = ', ', $excludes = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'assemble', array($sep, $excludes));

        return parent::assemble($sep, $excludes);
    }

    /**
     * {@inheritDoc}
     */
    public function populate($data = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'populate', array($data));

        return parent::populate($data);
    }

    /**
     * {@inheritDoc}
     */
    public function getArrayCopy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArrayCopy', array());

        return parent::getArrayCopy();
    }

    /**
     * {@inheritDoc}
     */
    public function setInputFilter(\Zend\InputFilter\InputFilterInterface $inputFilter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInputFilter', array($inputFilter));

        return parent::setInputFilter($inputFilter);
    }

    /**
     * {@inheritDoc}
     */
    public function getInputFilter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInputFilter', array());

        return parent::getInputFilter();
    }

}
