<?php

namespace DoctrineORMModule\Proxy\__CG__\Project\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class DocumentCategory extends \Project\Entity\DocumentCategory implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Project\\Entity\\DocumentCategory' . "\0" . 'location', '' . "\0" . 'Project\\Entity\\DocumentCategory' . "\0" . 'name', '' . "\0" . 'Project\\Entity\\DocumentCategory' . "\0" . 'description', '' . "\0" . 'Project\\Entity\\DocumentCategory' . "\0" . 'config', '' . "\0" . 'Project\\Entity\\DocumentCategory' . "\0" . 'partial', '' . "\0" . 'Project\\Entity\\DocumentCategory' . "\0" . 'compatibility', '' . "\0" . 'Project\\Entity\\DocumentCategory' . "\0" . 'active', '' . "\0" . 'Project\\Entity\\DocumentCategory' . "\0" . 'documentCategoryId');
        }

        return array('__isInitialized__', '' . "\0" . 'Project\\Entity\\DocumentCategory' . "\0" . 'location', '' . "\0" . 'Project\\Entity\\DocumentCategory' . "\0" . 'name', '' . "\0" . 'Project\\Entity\\DocumentCategory' . "\0" . 'description', '' . "\0" . 'Project\\Entity\\DocumentCategory' . "\0" . 'config', '' . "\0" . 'Project\\Entity\\DocumentCategory' . "\0" . 'partial', '' . "\0" . 'Project\\Entity\\DocumentCategory' . "\0" . 'compatibility', '' . "\0" . 'Project\\Entity\\DocumentCategory' . "\0" . 'active', '' . "\0" . 'Project\\Entity\\DocumentCategory' . "\0" . 'documentCategoryId');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (DocumentCategory $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function getConfig()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConfig', array());

        return parent::getConfig();
    }

    /**
     * {@inheritDoc}
     */
    public function getPartial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPartial', array());

        return parent::getPartial();
    }

    /**
     * {@inheritDoc}
     */
    public function getCompatibility()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompatibility', array());

        return parent::getCompatibility();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function setConfig($config)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConfig', array($config));

        return parent::setConfig($config);
    }

    /**
     * {@inheritDoc}
     */
    public function setPartial($partial)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPartial', array($partial));

        return parent::setPartial($partial);
    }

    /**
     * {@inheritDoc}
     */
    public function setCompatibility($compatibility)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompatibility', array($compatibility));

        return parent::setCompatibility($compatibility);
    }

    /**
     * {@inheritDoc}
     */
    public function getActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActive', array());

        return parent::getActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setActive($active)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActive', array($active));

        return parent::setActive($active);
    }

    /**
     * {@inheritDoc}
     */
    public function getDocumentCategoryId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getDocumentCategoryId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocumentCategoryId', array());

        return parent::getDocumentCategoryId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDocumentCategoryId($documentCategoryId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDocumentCategoryId', array($documentCategoryId));

        return parent::setDocumentCategoryId($documentCategoryId);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocation', array());

        return parent::getLocation();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocation($location)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocation', array($location));

        return parent::setLocation($location);
    }

}
