<?php

namespace DoctrineORMModule\Proxy\__CG__\Project\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Project extends \Project\Entity\Project implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Project\\Entity\\Project' . "\0" . 'name', '' . "\0" . 'Project\\Entity\\Project' . "\0" . 'co2', '' . "\0" . 'Project\\Entity\\Project' . "\0" . 'fuelTariff', '' . "\0" . 'Project\\Entity\\Project' . "\0" . 'rpi', '' . "\0" . 'Project\\Entity\\Project' . "\0" . 'epi', '' . "\0" . 'Project\\Entity\\Project' . "\0" . 'mcd', '' . "\0" . 'Project\\Entity\\Project' . "\0" . 'factorPrelim', '' . "\0" . 'Project\\Entity\\Project' . "\0" . 'factorOverhead', '' . "\0" . 'Project\\Entity\\Project' . "\0" . 'factorManagement', '' . "\0" . 'Project\\Entity\\Project' . "\0" . 'eca', '' . "\0" . 'Project\\Entity\\Project' . "\0" . 'maintenance', '' . "\0" . 'Project\\Entity\\Project' . "\0" . 'carbon', '' . "\0" . 'Project\\Entity\\Project' . "\0" . 'model', '' . "\0" . 'Project\\Entity\\Project' . "\0" . 'weighting', '' . "\0" . 'Project\\Entity\\Project' . "\0" . 'test', '' . "\0" . 'Project\\Entity\\Project' . "\0" . 'ibp', '' . "\0" . 'Project\\Entity\\Project' . "\0" . 'created', '' . "\0" . 'Project\\Entity\\Project' . "\0" . 'contracted', '' . "\0" . 'Project\\Entity\\Project' . "\0" . 'installed', '' . "\0" . 'Project\\Entity\\Project' . "\0" . 'completed', '' . "\0" . 'Project\\Entity\\Project' . "\0" . 'notes', '' . "\0" . 'Project\\Entity\\Project' . "\0" . 'client', '' . "\0" . 'Project\\Entity\\Project' . "\0" . 'sector', '' . "\0" . 'Project\\Entity\\Project' . "\0" . 'status', '' . "\0" . 'Project\\Entity\\Project' . "\0" . 'type', '' . "\0" . 'Project\\Entity\\Project' . "\0" . 'financeYears', '' . "\0" . 'Project\\Entity\\Project' . "\0" . 'financeProvider', '' . "\0" . 'Project\\Entity\\Project' . "\0" . 'contacts', '' . "\0" . 'Project\\Entity\\Project' . "\0" . 'collaborators', '' . "\0" . 'Project\\Entity\\Project' . "\0" . 'projectId', 'inputFilter');
        }

        return array('__isInitialized__', '' . "\0" . 'Project\\Entity\\Project' . "\0" . 'name', '' . "\0" . 'Project\\Entity\\Project' . "\0" . 'co2', '' . "\0" . 'Project\\Entity\\Project' . "\0" . 'fuelTariff', '' . "\0" . 'Project\\Entity\\Project' . "\0" . 'rpi', '' . "\0" . 'Project\\Entity\\Project' . "\0" . 'epi', '' . "\0" . 'Project\\Entity\\Project' . "\0" . 'mcd', '' . "\0" . 'Project\\Entity\\Project' . "\0" . 'factorPrelim', '' . "\0" . 'Project\\Entity\\Project' . "\0" . 'factorOverhead', '' . "\0" . 'Project\\Entity\\Project' . "\0" . 'factorManagement', '' . "\0" . 'Project\\Entity\\Project' . "\0" . 'eca', '' . "\0" . 'Project\\Entity\\Project' . "\0" . 'maintenance', '' . "\0" . 'Project\\Entity\\Project' . "\0" . 'carbon', '' . "\0" . 'Project\\Entity\\Project' . "\0" . 'model', '' . "\0" . 'Project\\Entity\\Project' . "\0" . 'weighting', '' . "\0" . 'Project\\Entity\\Project' . "\0" . 'test', '' . "\0" . 'Project\\Entity\\Project' . "\0" . 'ibp', '' . "\0" . 'Project\\Entity\\Project' . "\0" . 'created', '' . "\0" . 'Project\\Entity\\Project' . "\0" . 'contracted', '' . "\0" . 'Project\\Entity\\Project' . "\0" . 'installed', '' . "\0" . 'Project\\Entity\\Project' . "\0" . 'completed', '' . "\0" . 'Project\\Entity\\Project' . "\0" . 'notes', '' . "\0" . 'Project\\Entity\\Project' . "\0" . 'client', '' . "\0" . 'Project\\Entity\\Project' . "\0" . 'sector', '' . "\0" . 'Project\\Entity\\Project' . "\0" . 'status', '' . "\0" . 'Project\\Entity\\Project' . "\0" . 'type', '' . "\0" . 'Project\\Entity\\Project' . "\0" . 'financeYears', '' . "\0" . 'Project\\Entity\\Project' . "\0" . 'financeProvider', '' . "\0" . 'Project\\Entity\\Project' . "\0" . 'contacts', '' . "\0" . 'Project\\Entity\\Project' . "\0" . 'collaborators', '' . "\0" . 'Project\\Entity\\Project' . "\0" . 'projectId', 'inputFilter');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Project $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function getCo2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCo2', array());

        return parent::getCo2();
    }

    /**
     * {@inheritDoc}
     */
    public function getFuelTariff()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFuelTariff', array());

        return parent::getFuelTariff();
    }

    /**
     * {@inheritDoc}
     */
    public function getRpi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRpi', array());

        return parent::getRpi();
    }

    /**
     * {@inheritDoc}
     */
    public function getEpi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEpi', array());

        return parent::getEpi();
    }

    /**
     * {@inheritDoc}
     */
    public function getFactorPrelim()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFactorPrelim', array());

        return parent::getFactorPrelim();
    }

    /**
     * {@inheritDoc}
     */
    public function getFactorOverhead()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFactorOverhead', array());

        return parent::getFactorOverhead();
    }

    /**
     * {@inheritDoc}
     */
    public function getFactorManagement()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFactorManagement', array());

        return parent::getFactorManagement();
    }

    /**
     * {@inheritDoc}
     */
    public function getMcd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMcd', array());

        return parent::getMcd();
    }

    /**
     * {@inheritDoc}
     */
    public function getEca()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEca', array());

        return parent::getEca();
    }

    /**
     * {@inheritDoc}
     */
    public function getCarbon()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCarbon', array());

        return parent::getCarbon();
    }

    /**
     * {@inheritDoc}
     */
    public function getFund()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFund', array());

        return parent::getFund();
    }

    /**
     * {@inheritDoc}
     */
    public function getModel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModel', array());

        return parent::getModel();
    }

    /**
     * {@inheritDoc}
     */
    public function getWeighting()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWeighting', array());

        return parent::getWeighting();
    }

    /**
     * {@inheritDoc}
     */
    public function getMaintenance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaintenance', array());

        return parent::getMaintenance();
    }

    /**
     * {@inheritDoc}
     */
    public function getTest()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTest', array());

        return parent::getTest();
    }

    /**
     * {@inheritDoc}
     */
    public function getIbp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIbp', array());

        return parent::getIbp();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreated', array());

        return parent::getCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function getContracted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContracted', array());

        return parent::getContracted();
    }

    /**
     * {@inheritDoc}
     */
    public function getInstalled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInstalled', array());

        return parent::getInstalled();
    }

    /**
     * {@inheritDoc}
     */
    public function getCompleted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompleted', array());

        return parent::getCompleted();
    }

    /**
     * {@inheritDoc}
     */
    public function getNotes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNotes', array());

        return parent::getNotes();
    }

    /**
     * {@inheritDoc}
     */
    public function getClient()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClient', array());

        return parent::getClient();
    }

    /**
     * {@inheritDoc}
     */
    public function getSector()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSector', array());

        return parent::getSector();
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', array());

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function getFinanceYears()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFinanceYears', array());

        return parent::getFinanceYears();
    }

    /**
     * {@inheritDoc}
     */
    public function getFinanceProvider()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFinanceProvider', array());

        return parent::getFinanceProvider();
    }

    /**
     * {@inheritDoc}
     */
    public function getContacts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContacts', array());

        return parent::getContacts();
    }

    /**
     * {@inheritDoc}
     */
    public function getCollaborators()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCollaborators', array());

        return parent::getCollaborators();
    }

    /**
     * {@inheritDoc}
     */
    public function getProjectId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getProjectId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProjectId', array());

        return parent::getProjectId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function setCo2($co2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCo2', array($co2));

        return parent::setCo2($co2);
    }

    /**
     * {@inheritDoc}
     */
    public function setFuelTariff($fuelTariff)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFuelTariff', array($fuelTariff));

        return parent::setFuelTariff($fuelTariff);
    }

    /**
     * {@inheritDoc}
     */
    public function setRpi($rpi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRpi', array($rpi));

        return parent::setRpi($rpi);
    }

    /**
     * {@inheritDoc}
     */
    public function setEpi($epi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEpi', array($epi));

        return parent::setEpi($epi);
    }

    /**
     * {@inheritDoc}
     */
    public function setFactorPrelim($factorPrelim)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFactorPrelim', array($factorPrelim));

        return parent::setFactorPrelim($factorPrelim);
    }

    /**
     * {@inheritDoc}
     */
    public function setFactorOverhead($factorOverhead)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFactorOverhead', array($factorOverhead));

        return parent::setFactorOverhead($factorOverhead);
    }

    /**
     * {@inheritDoc}
     */
    public function setFactorManagement($factorManagement)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFactorManagement', array($factorManagement));

        return parent::setFactorManagement($factorManagement);
    }

    /**
     * {@inheritDoc}
     */
    public function setMcd($mcd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMcd', array($mcd));

        return parent::setMcd($mcd);
    }

    /**
     * {@inheritDoc}
     */
    public function setEca($eca)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEca', array($eca));

        return parent::setEca($eca);
    }

    /**
     * {@inheritDoc}
     */
    public function setCarbon($carbon)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCarbon', array($carbon));

        return parent::setCarbon($carbon);
    }

    /**
     * {@inheritDoc}
     */
    public function setFund($fund)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFund', array($fund));

        return parent::setFund($fund);
    }

    /**
     * {@inheritDoc}
     */
    public function setModel($model)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModel', array($model));

        return parent::setModel($model);
    }

    /**
     * {@inheritDoc}
     */
    public function setWeighting($weighting)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWeighting', array($weighting));

        return parent::setWeighting($weighting);
    }

    /**
     * {@inheritDoc}
     */
    public function setTest($test)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTest', array($test));

        return parent::setTest($test);
    }

    /**
     * {@inheritDoc}
     */
    public function setIbp($ibp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIbp', array($ibp));

        return parent::setIbp($ibp);
    }

    /**
     * {@inheritDoc}
     */
    public function setCreated(\DateTime $created)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreated', array($created));

        return parent::setCreated($created);
    }

    /**
     * {@inheritDoc}
     */
    public function setContracted(\DateTime $contracted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContracted', array($contracted));

        return parent::setContracted($contracted);
    }

    /**
     * {@inheritDoc}
     */
    public function setInstalled(\DateTime $installed)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInstalled', array($installed));

        return parent::setInstalled($installed);
    }

    /**
     * {@inheritDoc}
     */
    public function setCompleted(\DateTime $completed)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompleted', array($completed));

        return parent::setCompleted($completed);
    }

    /**
     * {@inheritDoc}
     */
    public function setNotes($notes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNotes', array($notes));

        return parent::setNotes($notes);
    }

    /**
     * {@inheritDoc}
     */
    public function setProjectId($projectId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProjectId', array($projectId));

        return parent::setProjectId($projectId);
    }

    /**
     * {@inheritDoc}
     */
    public function setMaintenance($maintenance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMaintenance', array($maintenance));

        return parent::setMaintenance($maintenance);
    }

    /**
     * {@inheritDoc}
     */
    public function setClient($client)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClient', array($client));

        return parent::setClient($client);
    }

    /**
     * {@inheritDoc}
     */
    public function setSector($sector)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSector', array($sector));

        return parent::setSector($sector);
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', array($type));

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function setFinanceYears($financeYears)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFinanceYears', array($financeYears));

        return parent::setFinanceYears($financeYears);
    }

    /**
     * {@inheritDoc}
     */
    public function setFinanceProvider($financeProvider)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFinanceProvider', array($financeProvider));

        return parent::setFinanceProvider($financeProvider);
    }

    /**
     * {@inheritDoc}
     */
    public function setContacts($contacts)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContacts', array($contacts));

        return parent::setContacts($contacts);
    }

    /**
     * {@inheritDoc}
     */
    public function setCollaborators($collaborators)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCollaborators', array($collaborators));

        return parent::setCollaborators($collaborators);
    }

    /**
     * {@inheritDoc}
     */
    public function populate($data = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'populate', array($data));

        return parent::populate($data);
    }

    /**
     * {@inheritDoc}
     */
    public function getArrayCopy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArrayCopy', array());

        return parent::getArrayCopy();
    }

    /**
     * {@inheritDoc}
     */
    public function setInputFilter(\Zend\InputFilter\InputFilterInterface $inputFilter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInputFilter', array($inputFilter));

        return parent::setInputFilter($inputFilter);
    }

    /**
     * {@inheritDoc}
     */
    public function getInputFilter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInputFilter', array());

        return parent::getInputFilter();
    }

}
