<?php

namespace DoctrineORMModule\Proxy\__CG__\Product\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Build extends \Product\Entity\Build implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Product\\Entity\\Build' . "\0" . 'name', '' . "\0" . 'Product\\Entity\\Build' . "\0" . 'leadtime', '' . "\0" . 'Product\\Entity\\Build' . "\0" . 'risk', '' . "\0" . 'Product\\Entity\\Build' . "\0" . 'buildId');
        }

        return array('__isInitialized__', '' . "\0" . 'Product\\Entity\\Build' . "\0" . 'name', '' . "\0" . 'Product\\Entity\\Build' . "\0" . 'leadtime', '' . "\0" . 'Product\\Entity\\Build' . "\0" . 'risk', '' . "\0" . 'Product\\Entity\\Build' . "\0" . 'buildId');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Build $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function getRisk()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRisk', array());

        return parent::getRisk();
    }

    /**
     * {@inheritDoc}
     */
    public function getBuildId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getBuildId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBuildId', array());

        return parent::getBuildId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function setRisk($risk)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRisk', array($risk));

        return parent::setRisk($risk);
    }

    /**
     * {@inheritDoc}
     */
    public function setBuildId($buildId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBuildId', array($buildId));

        return parent::setBuildId($buildId);
    }

    /**
     * {@inheritDoc}
     */
    public function getLeadtime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLeadtime', array());

        return parent::getLeadtime();
    }

    /**
     * {@inheritDoc}
     */
    public function setLeadtime($leadtime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLeadtime', array($leadtime));

        return parent::setLeadtime($leadtime);
    }

}
