<?php

namespace DoctrineORMModule\Proxy\__CG__\Contact\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Country extends \Contact\Entity\Country implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Contact\\Entity\\Country' . "\0" . 'name', '' . "\0" . 'Contact\\Entity\\Country' . "\0" . 'iso4217', '' . "\0" . 'Contact\\Entity\\Country' . "\0" . 'iso31662', '' . "\0" . 'Contact\\Entity\\Country' . "\0" . 'iso31663', '' . "\0" . 'Contact\\Entity\\Country' . "\0" . 'enabled', '' . "\0" . 'Contact\\Entity\\Country' . "\0" . 'countryId');
        }

        return array('__isInitialized__', '' . "\0" . 'Contact\\Entity\\Country' . "\0" . 'name', '' . "\0" . 'Contact\\Entity\\Country' . "\0" . 'iso4217', '' . "\0" . 'Contact\\Entity\\Country' . "\0" . 'iso31662', '' . "\0" . 'Contact\\Entity\\Country' . "\0" . 'iso31663', '' . "\0" . 'Contact\\Entity\\Country' . "\0" . 'enabled', '' . "\0" . 'Contact\\Entity\\Country' . "\0" . 'countryId');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Country $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getEnabled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnabled', array());

        return parent::getEnabled();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnabled($enabled)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnabled', array($enabled));

        return parent::setEnabled($enabled);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function getIso4217()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIso4217', array());

        return parent::getIso4217();
    }

    /**
     * {@inheritDoc}
     */
    public function getIso31662()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIso31662', array());

        return parent::getIso31662();
    }

    /**
     * {@inheritDoc}
     */
    public function getIso31663()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIso31663', array());

        return parent::getIso31663();
    }

    /**
     * {@inheritDoc}
     */
    public function getCountryId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getCountryId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountryId', array());

        return parent::getCountryId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function setIso4217($iso4217)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIso4217', array($iso4217));

        return parent::setIso4217($iso4217);
    }

    /**
     * {@inheritDoc}
     */
    public function setIso31662($iso31662)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIso31662', array($iso31662));

        return parent::setIso31662($iso31662);
    }

    /**
     * {@inheritDoc}
     */
    public function setIso31663($iso31663)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIso31663', array($iso31663));

        return parent::setIso31663($iso31663);
    }

    /**
     * {@inheritDoc}
     */
    public function setCountryId($countryId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCountryId', array($countryId));

        return parent::setCountryId($countryId);
    }

}
