<?php
$this->headLink()
    ->appendStylesheet('/assets/chosen-bootstrap/chosen/chosen.css')
    ->appendStylesheet('/assets/data-tables/DT_bootstrap.css')
    ->appendStylesheet('/assets/bootstrap-toggle-buttons/static/stylesheets/bootstrap-toggle-buttons.css');

$this->inlineScript()
    ->appendFile('/assets/data-tables/jquery.dataTables.js')
    ->appendFile('/assets/data-tables/DT_bootstrap.js')
    ->appendFile('/assets/chosen-bootstrap/chosen/chosen.jquery.min.js')
    ->appendFile('/assets/bootstrap-toggle-buttons/static/js/jquery.toggle.buttons.js')
    ->appendFile('/js/forms/space/edit.js');

echo $this->partial('partial/system/dialogs.phtml');




   
?>
<div id="myModal4" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel4" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel3">Add Note&nbsp;</h3>
    </div>
    <div class="modal-body">
        <div id="noteLoader" class="loader"></div>
        <p>
            Enter the note that you would like to add to the space in the box provided and then click on the Add Note button.
        </p>
        <div class="control-group">
        <form id="AddNoteForm" action="/client-<?php echo $project->getClient()->getClientId(); ?>/project-<?php echo $project->getProjectId(); ?>/space-<?php echo $space->getSpaceId(); ?>/addnote/">
            <div class="controls">
                <textarea class="span12" name="note" placeholder="enter your note here"></textarea>
            </div>
        </form>
        </div>   
        <div id="msgs3"></div>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true"><i class="icon-remove"></i> Cancel</button>
        <button class="btn btn-success" id="btn-save-note" aria-hidden="true"><i class="icon-plus"></i> Add Note</button>
    </div>
</div>
<div class="row-fluid">
    <div class="span12">
        <a href="<?php echo $this->url('project', array('action'=>'system', 'cid'=>$project->getClient()->getClientId(), 'pid'=>$project->getProjectId())); ?>" class="btn btn-default"><i class="icon-backward"></i> Back to system setup</a>
        <a href="javascript: location.reload();" class="btn btn-default"><i class="icon-refresh"></i> Reload Page</a>
        <div class="space10"></div>
    </div>
</div>

<div class="row-fluid">
    <div class="span12 ">
        <form id="DeleteNoteForm" action="/client-<?php echo $project->getClient()->getClientId(); ?>/project-<?php echo $project->getProjectId(); ?>/space-<?php echo $space->getSpaceId(); ?>/deletenote/">
        <div class="alert alert-info relative" id="space-notes">
            <div id="noteDeleteLoader" class="loader"></div>
            <button class="close" id="btn-add-note">+</button>
<?php 
$notes = $space->getNotes();
$cnt = 0;
if (!empty($notes)) {
    $notesArr  = json_decode($notes, true);
    if (!empty($notesArr)) {
?>
<?php
        foreach ($notesArr as $idx=>$note) {
            $cnt++;
            echo "<div><strong>Note:</strong> {$note} <a data-index=\"{$idx}\" href=\"javascript:\" class=\"delete-note\"><i class=\"icon-remove\"></i></a></div>";
            //echo (($cnt>1)?'<br />':'')."<strong>Note {$cnt}:</strong> {$note}. <a href=\"javascript:\"><i class=\"icon-remove\"></i></a>";
        }
?>
<?php
    } 
}

if ($cnt==0) {
    echo 'No notes added to space';
}
?>
        </div>
        </form>
    </div>
</div>
<div class="row-fluid">
    <div class="span12">
        <!-- BEGIN ORDERED LISTS PORTLET-->
        <div class="widget orange">
            <div class="widget-title">
                <h4><i class="icon-cog"></i> Space Details</h4>
                            <span class="tools">
                            <a href="javascript:;" class="icon-chevron-down"></a>
                            <a href="javascript:;" class="icon-remove"></a>
                            </span>
            </div>
            <div class="widget-body relative">
                <div id="spaceLoader" class="loader"></div>
                <?php echo $this->form()->openTag($formSpace); ?>
                <div class="control-group">
                    <label class="control-label">Name</label>
                    <div class="controls">
                        <?php echo $this->formElement($formSpace->get('name'));  ?>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">Building</label>
                    <div class="controls">
                        <?php echo $this->formElement($formSpace->get('building'));  ?>
                    </div>
                </div>
                <?php echo $this->form()->closeTag($formSpace); ?>
                <div id="msgs2"></div>
                Created <?php echo $space->getCreated()->format('l jS F Y \a\t\ H:i');  ?>
                <button class="btn btn-default" id="btn-update-space" style="float: right"><i class="icon-edit icon-white"></i> Update</button>
                <button class="btn btn-default" id="btn-refresh-space" style="float: right; margin-right: 6px"><i class="icon-refresh icon-white"></i> Refresh</button>
                <div class="clearfix"></div>
            </div>
        </div>
        <!-- END ORDERED LISTS PORTLET-->

    </div>
</div>

<div class="row-fluid">
    <div class="span12" id="right_column">
        <div class="widget blue">
            <div class="widget-title">
                <h4><i class="icon-reorder"></i> Ordered Lists</h4>
                            <span class="tools">
                            <a href="javascript:;" class="icon-chevron-down"></a>
                            <a href="javascript:;" class="icon-remove"></a>
                            </span>
            </div>
            
            <div class="widget-body relative">
                <div id="systemEditLoader" class="loader"></div>
                <div>
                    <div class="clearfix">
                        <div class="btn-group pull-left">
                            <button id="btn-add-product" class="btn green" style="margin-right: 4px">
                                Add Product <i class="icon-plus"></i>
                            </button>
                            <button id="btn-add-service" class="btn green">
                                Add Service <i class="icon-plus"></i>
                            </button>
                        </div>
                        <div class="btn-group pull-right">
                            <button class="btn dropdown-toggle" data-toggle="dropdown">Tools <i class="icon-angle-down"></i>
                            </button>
                            <ul class="dropdown-menu pull-right">
                                <li><a href="#">Print</a></li>
                                <li><a href="#">Save as PDF</a></li>
                                <li><a href="#">Export to Excel</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="space15"></div>
                    <table class="table table-striped table-hover table-bordered table-row-middle" id="system_tbl">
                        <thead>
                        <tr>
                            <th ><i class="icon-cog"></i> Product</th>
                            <th style="width: 60px">Qty</th>
                            <th style="width: 60px">Hrs</th>
                            <th style="width: 60px">PPU</th>
                            <th style="width: 60px">ICPU</th>
                            <th style="width: 50px" class="hidden-phone">LUX</th>
                            <th style="width: 50px" class="hidden-phone">OCC</th>
                            <th style="width: 60px">Retrofit</th>
                            <th style="width: 80px">Options</th>
                            <th style="width: 120px">Price (inc MCD)</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php 
                            $totalPriceMCD = 0;
                            if (!empty($systems)) {
                                $mcd = $project->getMCD();
                                foreach ($systems as $system) {
                                    $priceMCD = round($system['quantity'] * (round($system['ppu'] * (1-($mcd*$system['mcd'])), 2)),2);
                                    $totalPriceMCD+=$priceMCD;
                                    
                                    $description = !empty($system['legacyId'])?'<span class="label label-success popovers" '
                                            . 'data-content="Type: '.$system['category'].
                                            '<br />Details: '.$system['description'].
                                            '<br />Quantity: '.$system['legacyQuantity'].
                                            (!empty($system['legacyWatts'])?'<br />Rating: '.$system['legacyWatts'].'W':'').
                                            (!empty($system['legacyMcpu'])?'<br />Maintenance: &#163;'.number_format($system['legacyMcpu'],2):'').'" '
                                            . 'data-html="true" '
                                            . 'data-placement="left" '
                                            . 'data-original-title="Retrofit Details" '
                                            . 'data-trigger="hover">Yes</span>':'<span class="label label-important">No</span>';
                                    echo '<tr>'
                                        . '<td>'.$system['model'].'</td>'
                                        . '<td class="row-right">'.$system['quantity'].'</td>'
                                        . '<td class="row-right hidden-phone" class="row-right">'.$system['hours'].'</td>'
                                        . '<td class="row-right">'.$system['ppu'].'</td>'
                                        . '<td class="row-right">'.$system['ippu'].'</td>'
                                        . '<td class="hidden-phone">'.$system['lux'].'%</td>'
                                        . '<td class="hidden-phone">'.$system['occupancy'].'%</td>'
                                        . '<td>'.$description.'</td>'
                                        . '<td>'
                                            . (!$system['locked']?'<button class="btn btn-primary action-system-edit" data-systemid="'.$system['systemId'].'"><i class="icon-pencil"></i></button>&nbsp;'
                                            . '<button class="btn btn-danger action-system-delete" data-systemid="'.$system['systemId'].'"><i class="icon-remove"></i></button>&nbsp;':'locked')
                                            . '</td>'
                                        . '<td class="row-right">&#163;'.number_format($priceMCD,2).'</td>'
                                        . '</tr>';
                                }
                            }
                            
                        ?>
                        </tbody>
                        <tfoot>
                        <tr>
                            <th colspan="9">Total Price</th>
                            <th class="row-right">&#163;<?php echo number_format($totalPriceMCD,2); ?></th>
                        </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<!--<div class="row-fluid">
    <div class="span12">
        <div class="widget green">
            <div class="widget-title">
                <h4><i class="icon-lightbulb"></i> LED Controls</h4>
                            <span class="tools">
                            <a href="javascript:;" class="icon-chevron-down"></a>
                            <a href="javascript:;" class="icon-remove"></a>
                            </span>
            </div>
            <div class="widget-body relative">
                <form class="form-horizontal">
                    <div class="control-group">
                        <label class="control-label">LED (01-166-0139f4)</label>
                        <div class="controls">
                            <div class="text-toggle-button">
                                <input type="checkbox" data-identifier="01-166-0139f4" />
                            </div>
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label">LED (01-166-074f96)</label>
                        <div class="controls">
                            <div class="text-toggle-button">
                                <input type="checkbox" data-identifier="01-166-074f96" />
                            </div>
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label">LED (01-166-258ce3)</label>
                        <div class="controls">
                            <div class="text-toggle-button">
                                <input type="checkbox" data-identifier="01-166-258ce3" />
                            </div>
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label">LED (01-166-542f85)</label>
                        <div class="controls">
                            <div class="text-toggle-button">
                                <input type="checkbox" data-identifier="01-166-542f85" />
                            </div>
                        </div>
                    </div>
                    
                </form>
                <div class="clearfix"></div>
            </div>
        </div>

    </div>
</div><!-- -->