<?php

$this->inlineScript()
    ->appendFile('/js/forms/project/export.js')
    ;


$this->headStyle()->captureStart() 
?>
    .tbl-export-building input[type=checkbox] {
        margin:0 0 3px 0; 
        padding:0; 
    }
    .tbl-export-building label input[type=checkbox] {
        margin-right: 6px; 
    }
    
    .tbl-export-building label {
        margin:0; 
        padding:0;
    }
    
    
<?php 
$this->headStyle()->captureEnd();
?>
<div class="row-fluid">
    <div class="span12" id="right_column">
        <div class="widget blue">
            <div class="widget-title">
                <h4><i class="icon-cogs"></i> Space Configuration</h4>
                <span class="tools">
                <a href="javascript:;" class="icon-chevron-down"></a>
                <a href="javascript:;" class="icon-remove"></a>
                </span>
            </div>
            <div class="widget-body relative">
                <div id="systemEditLoader" class="loader"></div>
                <div>
                    <div class="clearfix">
                        <div class="btn-group pull-left">
                            <button id="btn-select-all" class="btn green" style="margin-right: 4px">
                                Show All Items <i class="icon-check"></i>
                            </button>
                            <button id="btn-deselect-all" class="btn green" style="margin-right: 4px">
                                Hide All Items <i class="icon-check-empty"></i>
                            </button>
                        </div>
                        <div class="btn-group pull-right">
                        </div>
                    </div>
                    <div class="space5"></div>
                    <form id="exportSystemDetails" class="form-nomargin" >
                    <?php
                    if (!empty($breakdown)) {
                        foreach ($breakdown as $buildingId => $building) {
                    ?>
                    <div class="space15"></div>
                    <table class="table table-striped table-bordered table-advance tbl-export-building" id="tbl-export-building-<?php echo $buildingId; ?>">
                        <thead>
                            <tr>
                                <th>
                                    <label><input type="checkbox" class="chbx-building"  id="chbx-building-<?php echo $buildingId; ?>"  data-buildingId="<?php echo $buildingId; ?>" />Building: <?php echo ($buildingId==0)?'Global':ucwords($building ['name']); ?></label>
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>
                        <?php 
                            foreach ($building ['spaces'] as $spaceId => $space) {
                                $root = !empty($space['root']);
                                
                        ?>
                                    <div class="div-export-space"> 
                                        <div class="alert alert-success">
                                            <label><input id="chbx-space-<?php echo $spaceId; ?>" class="chbx-space" type="checkbox" data-buildingId="<?php echo $buildingId; ?>" data-spaceId="<?php echo $spaceId; ?>" />Space: <?php echo ucwords ($space ['name']); ?></label>
                                        </div>
                                        <table class="table table-striped table-bordered table-advance table-hover tbl-export-system" id="tbl-export-system-<?php echo $spaceId; ?>">
                                            <thead>
                                                <tr>
                                                    <th style="width: 14px"></th>
                                                    <th style="width: 200px" class="">Product</th>
                                                    <th style="width: 60px" class="">Qty</th>
                                                    <th style="width: 60px" class="">Hrs</th>
                                                    <th class="">Legacy</th>
                                                    <th style="width: 100px" class="row-right">Total Cost</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <?php

                                    foreach ( $space['products'] as $systemId => $system) {
                                        $disabled = (!$root && ($system[2]==100));
                                        ?>
                                                <tr>
                                                    <td><input value="<?php echo $spaceId,'_',$systemId; ?>" name="systemId[]" class="chbx-system" type="checkbox" data-buildingId="<?php echo $buildingId; ?>" data-spaceId="<?php echo $spaceId; ?>" /></td>
                                                    <td class=""><?php echo ucwords ($system [4]); ?></td>
                                                    <td class=""><?php echo $system [5]; ?></td>
                                                    <td class=""><?php echo $system [6]; ?></td>
                                                    <td class=""><?php echo empty($system [8])?'-':ucwords($system [8]); ?></td>
                                                    <td class="row-right"><?php echo number_format($system [1],2); ?></td>
                                                </tr>
                                        <?php
                                    }
                                        ?>
                                            </tbody>  
                                        </table>
                                        <br class="clearfix" />
                                    </div>
                        <?php
                            }
                        ?>
                                </td>
                            </tr>
                        </tbody>
                    </table>

                            <?php
                        }
                    }

                    ?>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>