<?php
//$this->headLink()->appendStylesheet('/assets/data-tables/DT_bootstrap.css');

/*$this->inlineScript()
    ->appendFile('/assets/signalr/jquery.signalr-1.1.2.min.js')
    ->appendFile('https://testing.wattzo.com/api/realtime/hubs')
;/**/

$this->inlineScript()->captureStart();
echo <<<JS
var Sliders = function () {
// vertical slider
    $("#slider-vertical-red").slider({
        orientation: "vertical",
        range: "min",
        min: 0,
        max: 255,
        value: 0,
        slide: function (event, ui) {
            $("#slider-vertical-red-amount").text(ui.value);
        },
        change: function (event, ui) {
            channelChange('01-710-0ED7C7', ui.value);
        }
    });

    $("#slider-vertical-green").slider({
        orientation: "vertical",
        range: "min",
        min: 0,
        max: 255,
        value: 0,
        slide: function (event, ui) {
            $("#slider-vertical-green-amount").text(ui.value);
        },
        change: function (event, ui) {
            channelChange('01-710-38DA4C', ui.value);
        }
    });

    $("#slider-vertical-blue").slider({
        orientation: "vertical",
        range: "min",
        min: 0,
        max: 255,
        value: 0,
        slide: function (event, ui) {
            $("#slider-vertical-blue-amount").text(ui.value);
        },
        change: function (event, ui) {
            channelChange('01-710-57CF63', ui.value);
        }
    });

    $("#slider-vertical-white").slider({
        orientation: "vertical",
        range: "min",
        min: 0,
        max: 255,
        value: 0,
        slide: function (event, ui) {
            $("#slider-vertical-white-amount").text(ui.value);
        },
        change: function (event, ui) {
            channelChange('01-710-3ED970', ui.value);
        }
    });

    $("#slider-vertical-red-amount").text($("#slider-vertical-red").slider("value"));
    $("#slider-vertical-green-amount").text($("#slider-vertical-green").slider("value"));
    $("#slider-vertical-blue-amount").text($("#slider-vertical-blue").slider("value"));
    $("#slider-vertical-white-amount").text($("#slider-vertical-white").slider("value"));

    function channelChange(deviceId, value) {    
        CallRestAPI(
            'PUT',
            'hubs/'+hubId+'/devices/'+deviceId+'/level',
            'level='+value+'&rate=128',
            token
        );
        //console.log('Device: '+deviceId+' = '+value);
    }

   
    var hubId = "01-001-1CE70B";
    var token = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL3dhdHR6by5hY2Nlc3Njb250cm9sLndpbmRvd3MubmV0LyIsImF1ZCI6Imh0dHBzOi8vdGVzdGluZy53YXR0em8uY29tLyIsIm5iZiI6MTQxNTg5MTMyMiwiZXhwIjoyNTM0MDIzMDA3OTksImVtYWlsIjoiam9ubnkucC5jb29rQDhwb2ludDNsZWQuY28udWsiLCJ1bmlxdWVfbmFtZSI6Ikpvbm55IENvb2siLCJuYW1laWQiOiIxZGNiYzE4YjczNTU0OWE1ODdhMjRjNzNiZjYwNjFkMSIsImlkZW50aXR5cHJvdmlkZXIiOiJXYXR0em8ifQ.RKkiJ-xIdrUbbN382iIaXn8BiK14x3XA9XDAYk0i3lo';

    function CallRestAPI(method, endPoint, param, token)
    {
        var weblink = "https://testing.wattzo.com/api/"+endPoint;
        //console.log(weblink); return;
        
        $.ajax(
        {
            url : weblink,
            type : method,
            data: param,
            dataType: 'json',
            beforeSend: function (request)
            {
                if ((token!=undefined) && (token!=null)) {
                    request.setRequestHeader("Authorization", "Bearer "+token);
                }
            },
            crossDomain: true,
            success : function(result, textStatus, request)
            {
                //process the result
                console.log(result);
                console.log(textStatus);
                console.log(request.status);
                /*for (i in result.data) {
                    //console.log(result.data[i].id);
                }/**/
            },
            error : function(jqXHR, textStatus, errorThrown) {
                alert('Error: '+jqXHR.status);
                alert('ErrorThrown: '+errorThrown)
            }
        });
    }
}();
JS;
$this->inlineScript()->captureEnd();

?>

<div class="row-fluid">
    <div class="span12">
      <!-- BEGIN SLIDER PORTLET-->
      <div class="widget">
            <div class="widget-title">
               <h4><i class="icon-bar-chart"></i> jQuery UI Sliders </h4>
               <span class="tools">
                   <a href="javascript:;" class="icon-chevron-down"></a>
                   <a href="javascript:;" class="icon-remove"></a>
               </span>
            </div>
            <div class="widget-body">
                <table class="table sliders">
                    <tbody>

                    <tr>
                        <td style="width: 100px">
                            <div class="slider-vertical-value">
                                <span class="text-error">Red:</span> <span  class="slider-info" id="slider-vertical-red-amount"></span>
                            </div>
                            <div id="slider-vertical-red" class="slider bg-green" style="height: 250px;"></div>
                        </td>
                        <td style="width: 100px">
                            <div class="slider-vertical-value">
                                <span class="text-success">Green:</span> <span  class="slider-info" id="slider-vertical-green-amount"></span>
                            </div>
                            <div id="slider-vertical-green" class="slider bg-green" style="height: 250px;"></div>
                        </td>
                        <td style="width: 100px">
                            <div class="slider-vertical-value">
                               <span class="text-info">Blue:</span> <span  class="slider-info" id="slider-vertical-blue-amount"></span>
                            </div>
                            <div id="slider-vertical-blue" class="slider bg-green" style="height: 250px;"></div>
                        </td>
                        <td style="width: 100px">
                            <div class="slider-vertical-value">
                                White: <span  class="slider-info" id="slider-vertical-white-amount"></span>
                            </div>
                            <div id="slider-vertical-white" class="slider bg-green" style="height: 250px;"></div>
                        </td>
                        <td></td>
                    </tr>

                    </tbody>
                </table>
                
            </div>
      </div>
      <!-- END SLIDER PORTLET-->
    </div>
</div>

