<div class="row-fluid">
    <!--BEGIN METRO STATES-->
    <div class="metro-nav">
        <div class="metro-nav-block nav-block-blue">
            <a data-original-title="" href="/playground/routemapping/">
                <i class="icon-truck"></i>
                <div class="info">Maps</div>
                <div class="status">Route Mapping</div>
            </a>
        </div>
    </div>
</div>