<?php
$this->headLink()
    ->appendStylesheet('/assets/data-tables/DT_bootstrap.css');

$this->inlineScript()
    ->appendFile('/assets/data-tables/jquery.dataTables.js')
    ->appendFile('/assets/data-tables/DT_bootstrap.js')
    ->appendFile('/js/forms/task/list.js')
    ;
?>
<div class="row-fluid">
    <!--BEGIN METRO STATES-->
    <div class="metro-nav">

        <div class="metro-nav-block  nav-block-purple">
            <a href="#modalAddTask" data-original-title="" role="button" data-toggle="modal">
                <div class="text-center">
                    <i class="icon-plus-sign-alt"></i>
                </div>
                <div class="status">Create Task</div>
            </a>
        </div>
    </div>
    <div class="space10"></div>
    <!--END METRO STATES-->
</div>
<div class="row-fluid">
    <div class="span12">
        <!-- BEGIN BASIC PORTLET-->
        <div class="widget blue">
            <div class="widget-title">
                <h4><i class="icon-tasks"></i> My Tasks</h4>
                <span class="tools">
                    <a href="javascript:;" class="icon-chevron-down"></a>
                </span>
            </div>
            <div class="widget-body relative">
                <div id="wizardLoader" class="loader"></div>
                <table class="table table-advance table-bordered table-striped table-hover" id="tbl-tasks">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Type</th>
                            <th class="hidden-phone">Description</th>
                            <th class="hidden-phone">Originator</th>
                            <th>Target Date</th>
                            <th>Status</th>
                            <th>&nbsp;</th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
        <!-- END BLANK PAGE PORTLET-->
    </div>
</div>
<?php echo $this->partial('partial/task/add.phtml'); ?>