<?php 
    $client = $project->getClient();
    $includeVAT = !empty($form['vat']);
    echo $this->partial('partial/project/docs/headers/quotehead.phtml'); 
?>
<div>
    <style>
        table.quote_details {
            width: 100%;
        }

        table.quote_details {
            border-spacing: 0;
        }

        table.quote_details thead {
            border-bottom: 1px #ccc solid;
        }

        table.quote_details tbody tr td {
            border-bottom: 1px #ccc solid;
        }

        table.quote_details tfoot tr td {
            border-bottom: 1px #ccc solid;
        }

        table.quote_details tfoot tr th {
            border-bottom: 1px #ccc solid;
        }

    </style>
    <?php
        switch ($billstyle) {
            case 2: // Standard Layout (Without descriptions)
                $tblHdr = 
                //'<th class="left" style="width: 40px">Id</th>
                '<th class="left" >Product</th>
                <th class="right" style="width: 100px">Quantity</th>
                <th class="right" style="width: 100px">Unit Price (&#163;)</th>
                <th class="right" style="width: 120px">Total Price (&#163;)</th>';
                $cols = 4;
                break;
            case 3: // Quantites
                $tblHdr = 
                    //'<th class="left" style="width: 40px">Id</th>
                '<th class="left" style="width: 240px">Product</th>
                <th class="left">Description</th>
                <th class="right" style="width: 100px">Quantity</th>';
                $cols = 3;
                break;
            case 4: // architectural
                $tblHdr = '<th class="left" >Product Description</th>
                <th class="right" style="width: 80px">Specified</th>
                <th class="right" style="width: 80px">Achievable</th>
                <th class="right" style="width: 90px">Price (&#163;)</th>';
                $cols = 4;
                break;
            default: // Standard Layout (With Descriptions)
                $tblHdr = 
                //'<th class="left" style="width: 40px">Id</th>
                '<th class="left" style="width: 230px">Product</th>
                <th class="left">Description</th>
                <th class="right" style="width: 100px">Quantity</th>
                <th class="right" style="width: 100px">Unit Price (&#163;)</th>
                <th class="right" style="width: 120px">Total Price (&#163;)</th>';
                $cols = 5;
                break;
        }
    ?>
    <table class="quote_details">
        <thead>
            <tr>
                <?php echo $tblHdr; ?>
            </tr>
        </thead>
        <tbody>
            <?php
                if (!empty($breakdown)) {
                    foreach ($breakdown as $buildingId=>$building) {
                        foreach ($building['spaces'] as $spaceId=>$space) {
                            foreach ($space['products'] as $systemId=>$system) {
                                if ($system[2]==3) {
                                    $attributes = json_decode($system[16]);
                                    echo '<tr>'
                                            //. '<td class="left">'.$system[3].'</td>'
                                            . '<td class="left">'.(!empty($system[17])?$system[17].' - ':'').$system[8].' <span style="font-size:10px;">['.$system[3].']</span></td>'
                                            . '<td class="right">'.number_format(($attributes->sLen/1000), 2).'m</td>'
                                            . '<td class="right">'.number_format(($attributes->dLen/1000), 2).'m</td>'
                                            . '<td class="right">'.number_format($system[1], 2).'</td></tr>';
                                }
                            }
                        }
                    }
                }
            
                $installation = 0;
                $delivery = 0;
                $access = 0;
                $other = 0;
                $ibptotal = 0;
                $total = 0;
                $totalProduct = 0;
                    
                

                if (!empty($billitems)) {
                    foreach ($billitems as $item) {
                        $ibp = 0;
                        if (!$item['service']) { // echo products
                            $ppu = round($item['ppu'] * (1-$project->getMcd()),2);
                            $price = $item['priceMCD'];// round($item['price']* (1-$project->getMcd()),2);
                            if ($project->getIbp()) {
                                $ibp=round($price * 0.018, 2); 
                                $ibptotal+=$ibp;
                            }

                            switch ($billstyle) {
                                case 2:
                                    echo '<tr>'
                                        //. '<td class="left">'.$item['productId'].'</td>'
                                        . '<td class="left">'.$item['model'].' <span style="font-size:10px;">['.$item['productId'].']</span></td>'
                                        . '<td class="right">'.$item['quantity'].'</td>'
                                        . '<td class="right">'.number_format($ppu, 2).'</td>'
                                        . '<td class="right">'.number_format($price, 2).'</td></tr>';
                                    break;
                                case 3:
                                    echo '<tr>'
                                        //. '<td class="left">'.$item['productId'].'</td>'
                                        . '<td class="left">'.$item['model'].' <span style="font-size:10px;">['.$item['productId'].']</span></td>'
                                        . '<td class="left">'.$item['description'].'</td>'
                                        . '<td class="right">'.$item['quantity'].'</td></tr>';
                                    break;
                                case 4:
                                    if ($item['typeId']!=3) { // ignore architectural
                                        echo '<tr>'
                                            //. '<td class="left">'.$item['productId'].'</td>'
                                            . '<td class="left">'.$item['description'].' <span style="font-size:10px;">['.$item['productId'].']</span></td>'
                                            . '<td class="right">&nbsp;</td>'
                                            . '<td class="right">'.$item['quantity'].' units</td>'
                                            . '<td class="right">'.number_format($price, 2).'</td></tr>';
                                    }
                                break;
                                default:
                                    echo '<tr>'
                                        //. '<td class="left">'.$item['productId'].'</td>'
                                        . '<td class="left">'.$item['model'].' <span style="font-size:10px;">['.$item['productId'].']</span></td>'
                                        . '<td class="left">'.$item['description'].'</td>'
                                        . '<td class="right">'.$item['quantity'].'</td>'
                                        . '<td class="right">'.number_format($ppu, 2).'</td>'
                                        . '<td class="right">'.number_format($price, 2).'</td></tr>';
                                break;
                            }
                            
                            
                            $totalProduct+=$price;
                            
                        } else {
                            $ppu = $item['ppu'];
                            $price = $item['price'];
                            if($item['typeId'] == 100) {
                                $installation+=$price; // type 100 is an installation product
                            } elseif($item['typeId'] == 101) {
                                $delivery+=$price; // type 100 is an installation product
                            } elseif($item['typeId'] == 102) {
                                $access+=$price; // type 100 is an installation product
                            } else {
                                $other+=$price; // type 100 is an installation product
                            }
                        }
                        $total+=($price+$ibp);
                    }
                }

            ?>
        </tbody>
        <tfoot>
            <tr>
                <td colspan="<?php echo $cols; ?>" >&nbsp;</td>
            </tr>
            <tr>
                <th colspan="<?php echo ($cols-1); ?>" class="left">Total Product Cost</th>
                <td class="right"><?php echo number_format($totalProduct, 2); ?></td>
            </tr>
            <?php if ($installation) { ?>
            <tr>
                <th colspan="<?php echo ($cols-1); ?>" class="left">Installation Cost</th>
                <td class="right"><?php echo number_format($installation, 2); ?></td>
            </tr>
            <?php } ?>
            <?php if ($delivery) { ?>
            <tr>
                <th colspan="<?php echo ($cols-1); ?>" class="left">Delivery Cost</th>
                <td class="right"><?php echo number_format($delivery, 2); ?></td>
            </tr>
            <?php } ?>
            <?php if ($ibptotal) { ?>
            <tr>
                <th colspan="<?php echo ($cols-1); ?>" class="left">Insurance Backed Premium Cost</th>
                <td class="right"><?php echo number_format($ibptotal, 2); ?></td>
            </tr>
            <?php } ?>
            <?php if ($access) { ?>
            <tr>
                <th colspan="<?php echo ($cols-1); ?>" class="left">Delivery Cost</th>
                <td class="right"><?php echo number_format($access, 2); ?></td>
            </tr>
            <?php } ?>
            <?php if ($other) { ?>
            <tr>
                <th colspan="<?php echo ($cols-1); ?>" class="left">Other Costs</th>
                <td class="right"><?php echo number_format($other, 2); ?></td>
            </tr>
            <?php } ?>
            <tr>
                <td colspan="<?php echo $cols; ?>" >&nbsp;</td>
            </tr>
            <tr>
                <th colspan="<?php echo ($cols-1); ?>" class="left">Total Cost <?php if (!empty($includeVAT)) echo 'Excluding VAT'; ?></th>
                <td class="right"><?php echo number_format($total, 2); ?></td>
            </tr>
<?php 
if (!empty($includeVAT)){ 
$vat = round($total*0.2,2);
?>
            <tr>
                <th colspan="<?php echo ($cols-1); ?>" class="left">VAT @ 20%</th>
                <td class="right"><?php echo number_format($vat,2); ?></td>
            </tr>
            <tr>
                <th colspan="<?php echo ($cols-1); ?>" class="left">Total Cost (Including VAT)</th>
                <td class="right"><?php echo number_format($total+$vat,2); ?></td>
            </tr>
<?php 
}
?>                    
        </tfoot>
    </table>
    <p>
        This is a quotation on the goods named, subject to 8point3 Ltd's standard terms & conditions. Costs are exclusive of
        setup and commissioning of sensor and lighting controls unless itemised above.
    </p>
    <p>
        To accept this quotation, please sign and date below and return by email to: orders@8point3led.co.uk or by post
        to: Sales Department, 8point3 Limited, Suscon, Brunel Way, The Bridge, Dartford, Kent, DA1 5FW
    </p>
    <p>
        Should you have any queries regarding this quotation then please contact <?php echo $user->getName(); ?> on 01322 270 400 quoting reference <strong><?php echo str_pad($project->getClient()->getClientId(), 5, "0", STR_PAD_LEFT).'-'.str_pad($project->getProjectId(), 5, "0", STR_PAD_LEFT);
            if (isset ($invoiceNo)) {
                echo ' / '.$invoiceNo;
            }
        ?></strong>.
    </p>
    <?php 
        echo $this->partial('partial/project/docs/footers/quotefoot.phtml'); 
    ?>
</div>