<?php

$this->inlineScript()
    ->appendFile('/js/forms/project/trial.js')
    ;


$this->headStyle()->captureStart() 
?>
    .tbl-export-building input[type=checkbox] {
        margin:0 0 3px 0; 
        padding:0; 
    }
    .tbl-export-building label input[type=checkbox] {
        margin-right: 6px; 
    }
    
    .tbl-export-building label {
        margin:0; 
        padding:0;
    }
    
    
<?php 
$this->headStyle()->captureEnd();


$this->inlineScript()->captureStart();
echo <<<JS

JS;
$this->inlineScript()->captureEnd();
?>
<?php if ($this->isGranted('project.create')) { ?>
<div id="modalExportProject" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel1" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel3">Export Project&nbsp;</h3>
    </div>
    <div class="modal-body">
        <div id="exportProjectLoader" class="loader"></div>
        <?php echo $this->form()->openTag($form); ?>
        <p>
            Please enter the name of the trial that you would like to create.
        </p>
        <div class="control-group">
            <label class="control-label">Trial Name:</label>
            <div class="controls">
                <?php echo $this->formElement($form->get('name'));  ?>
            </div>
        </div>
        <?php echo $this->form()->closeTag($form); ?>
        <div class="alert alert-warning no-margin-bot">
            <strong>Important 1:</strong> Trial will be created and marked as pending<br />
            <strong>Important 2:</strong> Trial will need to be activated subsequent to creation.<br />
        </div>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true"><i class="icon-remove"></i> Cancel</button>
        <button class="btn btn-success" id="btn-confirm-exportproject" aria-hidden="true"><i class="icon-plus"></i> Create</button>
    </div>
</div>
<div class="row-fluid">
    <!--BEGIN METRO STATES-->
    <div class="metro-nav metro-fix-view">

        <div class="metro-nav-block  nav-block-orange">
            <a href="#modalExportProject" data-toggle="modal" href="javascript:" data-original-title="" id="btn-config-save">
                <div class="info">+</div>
                <div class="text-center">
                    <i class="icon-dropbox"></i>
                </div>
                <div class="status">Create Trial</div>
            </a>
        </div>
    </div>
    <div class="space10"></div>
    <!--END METRO STATES-->
</div>
<?php } ?>
<div class="row-fluid">
    <div class="span12" id="right_column">
        <div class="widget blue">
            <div class="widget-title">
                <h4><i class="icon-reorder"></i> Space Configuration</h4>
                <span class="tools">
                <a href="javascript:;" class="icon-chevron-down"></a>
                <a href="javascript:;" class="icon-remove"></a>
                </span>
            </div>
            <div class="widget-body relative">
                <div id="systemEditLoader" class="loader"></div>
                <div>
                    <div class="clearfix">
                        <div class="btn-group pull-left">
                            <button id="btn-select-all" class="btn green" style="margin-right: 4px">
                                Select All Items <i class="icon-check"></i>
                            </button>
                            <button id="btn-deselect-all" class="btn green" style="margin-right: 4px">
                                Deselect All Items <i class="icon-check-empty"></i>
                            </button>
                        </div>
                        <div class="btn-group pull-right">
                        </div>
                    </div>
                    <div class="space5"></div>
                    <form id="exportSystemDetails" class="form-nomargin" >
                    <?php
                    if (!empty($breakdown)) {
                        foreach ($breakdown as $buildingId => $building) {
                    ?>
                    <div class="space15"></div>
                    <table class="table table-striped table-bordered table-advance tbl-export-building" id="tbl-export-building-<?php echo $buildingId; ?>">
                        <thead>
                            <tr>
                                <th>
                                    <label><input type="checkbox" class="chbx-building"  id="chbx-building-<?php echo $buildingId; ?>"  data-buildingId="<?php echo $buildingId; ?>" />Building: <?php echo ($buildingId==0)?'Global':ucwords($building ['name']); ?></label>
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>
                        <?php 
                            foreach ($building ['spaces'] as $spaceId => $space) {
                                $root = !empty($space['root']);
                                
                        ?>
                                    <div class="div-export-space"> 
                                        <div class="alert alert-success">
                                            <label><input id="chbx-space-<?php echo $spaceId; ?>" class="chbx-space" type="checkbox" data-buildingId="<?php echo $buildingId; ?>" data-spaceId="<?php echo $spaceId; ?>" />Space: <?php echo ucwords ($space ['name']); ?></label>
                                        </div>
                                        <table class="table table-striped table-bordered table-advance table-hover tbl-export-system table-row-middle" id="tbl-export-system-<?php echo $spaceId; ?>">
                                            <thead>
                                                <tr>
                                                    <th style="width: 14px"></th>
                                                    <th style="width: 200px" class="">Product</th>
                                                    <th style="width: 60px" class="">Qty</th>
                                                    <th style="width: 80px" class="">Trial PPU</th>
                                                    <th style="width: 80px" class="">RRP</th>
                                                    <th class="">Legacy</th>
                                                    <th style="width: 80px" class="row-right">Pwr Save</th>
                                                    <th style="width: 100px" class="row-right">Monthly Cost</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <?php

                                    foreach ( $space['products'] as $systemId => $system) {
                                        ?>
                                                <tr>
                                                    <td><input value="<?php echo $spaceId,'_',$systemId; ?>" name="systemId[]" class="chbx-system" type="checkbox" data-buildingId="<?php echo $buildingId; ?>" data-spaceId="<?php echo $spaceId; ?>" /></td>
                                                    <td class=""><?php echo ucwords ($system [3]); ?></td>
                                                    <td class=""><input class="span12" type="number" min="0" value="<?php echo $system [4]; ?>" name="quantity[]" style="margin:0;" /></td>
                                                    <td class=""><input class="span12" type="number" min="0" step="0.01" value="<?php echo $system [1]; ?>" name="tppu[]" style="margin:0;" /></td>
                                                    <td class=""><?php echo $system [0]; ?></td>
                                                    <td class=""><?php echo empty($system [5])?'-':$system [6].' x '.ucwords($system [5]); ?></td>
                                                    <td class="row-right"><?php echo $system [11]; ?>%</td>
                                                    <td class="row-right"><?php echo number_format($system [1] * $system [4],2); ?></td>
                                                </tr>
                                        <?php
                                    }
                                        ?>
                                            </tbody>  
                                        </table>
                                        <br class="clearfix" />
                                    </div>
                        <?php
                            }
                        ?>
                                </td>
                            </tr>
                        </tbody>
                    </table>

                            <?php
                        }
                    }

                    ?>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>