<?php
// additional css
$this->headLink()
    ->appendStylesheet('/assets/bootstrap/css/bootstrap-fileupload.css')
    ->appendStylesheet('/assets/fullcalendar/fullcalendar/bootstrap-fullcalendar.css')
    ->appendStylesheet('/assets/jquery-easy-pie-chart/jquery.easy-pie-chart.css');

//additional scripts
$this->inlineScript()
    ->appendFile('/assets/fullcalendar/fullcalendar/fullcalendar.min.js')
    ->appendFile('/assets/jquery-easy-pie-chart/jquery.easy-pie-chart.js')
    ->appendFile('/js/jquery.sparkline.js')
    ->appendFile('/assets/chart-master/Chart.js')

//page specific scripts
    ->appendFile('/js/easy-pie-chart.js')
    ->appendFile('/js/sparkline-chart.js')
    ->appendFile('/js/home-page-calender.js')
    ->appendFile('/js/chartjs.js');
    

?>
<div class="row-fluid">
    <!--BEGIN METRO STATES-->
    <div class="metro-nav">
        <div class="metro-nav-block nav-block-orange">
            <a data-original-title="" href="#">
                <i class="icon-user"></i>
                <div class="info">Setup</div>
                <div class="status">My Profile</div>
            </a>
        </div>
        <div class="metro-nav-block nav-block-yellow">
            <a data-original-title="" href="#">
                <i class="icon-tags"></i>
                <div class="info">2</div>
                <div class="status">Jobs</div>
            </a>
        </div>
        <div class="metro-nav-block nav-block-grey">
            <a data-original-title="" href="#">
                <i class="icon-comments-alt"></i>
                <div class="info">49</div>
                <div class="status">Activity Log</div>
            </a>
        </div>
        <div class="metro-nav-block nav-block-blue double">
            <a data-original-title="" href="<?php echo $this->url('clients'); ?>">
                <i class="icon-eye-open"></i>
                <div class="info"><?php echo $info['activeClients']; ?> Owned</div>
                <div class="status">Clients</div>
            </a>
        </div>
        <div class="metro-nav-block nav-block-red">
            <a data-original-title="" href="#">
                <i class="icon-bar-chart"></i>
                <div class="info">Reports</div>
                <div class="status">Reporting and Statistics</div>
            </a>
        </div>
    </div>
    <div class="metro-nav">
        <div class="metro-nav-block nav-block-blue">
            <a data-original-title="" href="#">
                <i class="icon-shopping-cart"></i>
                <div class="info">Assets</div>
                <div class="status">Tracking</div>
            </a>
        </div>
        <div class="metro-nav-block nav-block-green double">
            <a data-original-title="" href="/project">
                <i class="icon-tasks"></i>
                <div class="info"><?php echo $info['activeProjects']; ?> Active</div>
                <div class="status">My Projects</div>
            </a>
        </div>
        <div class="metro-nav-block nav-block-orange">
            <a data-original-title="" href="#">
                <i class="icon-envelope"></i>
                <div class="info">123</div>
                <div class="status">Messages</div>
            </a>
        </div>
        <div class="metro-nav-block nav-block-purple">
            <a data-original-title="" href="#">
                <i class="icon-remove-sign"></i>
                <div class="info">0</div>
                <div class="status">Cancelled Projects</div>
            </a>
        </div>
        <div class="metro-nav-block nav-block-grey ">
            <a data-original-title="" href="#">
                <i class="icon-external-link"></i>
                <div class="info">&#163;0.00</div>
                <div class="status">Total Monthly Sales</div>
            </a>
        </div>
    </div>
    <div class="space10"></div>
    <!--END METRO STATES-->
</div>
<div class="row-fluid">
    <div class="span7 responsive" data-tablet="span7 fix-margin" data-desktop="span7">
        <!-- BEGIN CALENDAR PORTLET-->
        <div class="widget yellow">
            <div class="widget-title">
                <h4><i class="icon-calendar"></i> Calendar</h4>
                <span class="tools">
                    <a href="javascript:;" class="icon-chevron-down"></a>
                    <a href="javascript:;" class="icon-remove"></a>
                </span>
            </div>
            <div class="widget-body">
                <div id="calendar" class="has-toolbar"></div>
            </div>
        </div>
        <!-- END CALENDAR PORTLET-->
    </div>
    <div class="span5">
        <!-- BEGIN PROGRESS PORTLET-->
        <div class="widget purple">
            <div class="widget-title">
                <h4><i class="icon-tasks"></i> Task In progress </h4>
                <span class="tools">
                    <a href="javascript:;" class="icon-chevron-down"></a>
                    <a href="javascript:;" class="icon-remove"></a>
                </span>
            </div>
            <div class="widget-body">
                <ul class="unstyled">
                    <li>
                        <span class="btn btn-inverse"> <i class="icon-refresh"></i></span>  Update Jquery <strong class="label"> 48%</strong>
                        <div class="space10"></div>
                        <div class="progress">
                            <div style="width: 48%;" class="bar"></div>
                        </div>
                    </li>
                    <li>
                        <span class="btn btn-inverse"> <i class="icon-check"></i></span>  Update font awesome <strong class="label label-success"> 85%</strong>
                        <div class="space10"></div>
                        <div class="progress progress-success">
                            <div style="width: 85%;" class="bar"></div>
                        </div>
                    </li>
                    <li>
                        <span class="btn btn-inverse"> <i class="icon-fire"></i></span>  Update CSS3 <strong class="label label-important"> 65%</strong>
                        <div class="space10"></div>
                        <div class="progress progress-danger">
                            <div style="width: 65%;" class="bar"></div>
                        </div>
                    </li>

                </ul>
            </div>
        </div>
        <!-- END PROGRESS PORTLET-->
        <!-- BEGIN ALERTS PORTLET-->
        <div class="widget orange">
            <div class="widget-title">
                <h4><i class="icon-bell-alt"></i> Alerts</h4>
                <span class="tools">
                <a class="icon-chevron-down" href="javascript:;"></a>
                <a class="icon-remove" href="javascript:;"></a>
                </span>
            </div>
            <div class="widget-body">
                <div class="alert">
                    <button data-dismiss="alert" class="close">×</button>
                    <strong>Warning!</strong> Best check yo self, you're not looking too good.
                </div>
                <div class="alert alert-success">
                    <button data-dismiss="alert" class="close">×</button>
                    <strong>Success!</strong> You successfully read this important message.
                </div>
                <div class="alert alert-info">
                    <button data-dismiss="alert" class="close">×</button>
                    <strong>Info!</strong> Heads up! This alert needs your attention.
                </div>
                <div class="alert alert-error">
                    <button data-dismiss="alert" class="close">×</button>
                    <strong>Error!</strong> Change a few things. Please submit again.
                </div>
            </div>
        </div>
        <!-- END ALERTS PORTLET-->
    </div>
</div>
<div class="row-fluid">
     <div class="span6">
         <!-- BEGIN NOTIFICATIONS PORTLET-->
         <div class="widget blue">
             <div class="widget-title">
                 <h4><i class="icon-bell"></i> Notification </h4>
               <span class="tools">
                   <a href="javascript:;" class="icon-chevron-down"></a>
                   <a href="javascript:;" class="icon-remove"></a>
               </span>
             </div>
             <div class="widget-body">
                 <ul class="item-list scroller padding"  style="overflow: hidden; width: auto; height: 320px;" data-always-visible="1">
                     <li>
                         <span class="label label-success"><i class="icon-bell"></i></span>
                         <span>New user registered.</span>
                         <div class="pull-right">
                             <span class="small italic ">Just now</span>

                         </div>
                     </li>
                     <li>
                         <span class="label label-success"><i class="icon-bell"></i></span>
                         <span>New order received.</span>
                         <div class="pull-right">
                             <span class="small italic ">15 mins ago</span>

                         </div>
                     </li>
                     <li>
                         <span class="label label-warning"><i class="icon-bullhorn"></i></span>
                         <span>Alerting a user account balance.</span>
                         <div class="pull-right">
                             <span class="small italic ">3 hours ago</span>

                         </div>
                     </li>
                     <li>
                         <span class="label label-important"><i class=" icon-bug"></i></span>
                         <span>Alerting administrators staff.</span>
                         <div class="pull-right">
                             <span class="small italic ">9 mins ago</span>

                         </div>
                     </li>
                     <li>
                         <span class="label label-important"><i class=" icon-bug"></i></span>
                         <span>Messages are not sent to users.</span>
                         <div class="pull-right">
                             <span class="small italic ">10 hours ago</span>

                         </div>
                     </li>
                     <li>
                         <span class="label label-warning"><i class="icon-bullhorn"></i></span>
                         <span>Web server #12 failed to relosd.</span>
                         <div class="pull-right">
                             <span class="small italic ">3 mins ago</span>

                         </div>
                     </li>
                     <li>
                         <span class="label label-success"><i class="icon-bell"></i></span>
                         <span>New order received.</span>
                         <div class="pull-right">
                             <span class="small italic ">40 mins ago</span>

                         </div>
                     </li>
                     <li>
                         <span class="label label-warning"><i class="icon-bullhorn"></i></span>
                         <span>Alerting a user account balance.</span>
                         <div class="pull-right">
                             <span class="small italic ">1 hours ago</span>

                         </div>
                     </li>
                     <li>
                         <span class="label label-important"><i class=" icon-bug"></i></span>
                         <span>Alerting administrators staff.</span>
                         <div class="pull-right">
                             <span class="small italic ">1 mins ago</span>

                         </div>
                     </li>
                     <li>
                         <span class="label label-important"><i class=" icon-bug"></i></span>
                         <span>Messages are not sent to users.</span>
                         <div class="pull-right">
                             <span class="small italic ">11 hours ago</span>

                         </div>
                     </li>
                     <li>
                         <span class="label label-warning"><i class="icon-bullhorn"></i></span>
                         <span>Web server #12 failed to relosd.</span>
                         <div class="pull-right">
                             <span class="small italic ">1 day ago</span>

                         </div>
                     </li>
                     <li>
                         <span class="label label-success"><i class="icon-bell"></i></span>
                         <span>New order received.</span>
                         <div class="pull-right">
                             <span class="small italic ">10 mins ago</span>

                         </div>
                     </li>
                     <li>
                         <span class="label label-warning"><i class="icon-bullhorn"></i></span>
                         <span>Alerting a user account balance.</span>
                         <div class="pull-right">
                             <span class="small italic ">3 hours ago</span>

                         </div>
                     </li>
                     <li>
                         <span class="label label-important"><i class=" icon-bug"></i></span>
                         <span>Alerting administrators support staff.</span>
                         <div class="pull-right">
                             <span class="small italic ">6 hours ago</span>

                         </div>
                     </li>
                     <li>
                         <span class="label label-important"><i class=" icon-bug"></i></span>
                         <span>Messages are not sent to users.</span>
                         <div class="pull-right">
                             <span class="small italic ">3 days ago</span>

                         </div>
                     </li>
                     <li>
                         <span class="label label-warning"><i class="icon-bullhorn"></i></span>
                         <span>Web server #12 failed to relosd.</span>
                         <div class="pull-right">
                             <span class="small italic ">1 day ago</span>

                         </div>
                     </li>
                 </ul>
                 <div class="space10"></div>
                 <a href="#" class="pull-right">View all notifications</a>
                 <div class="clearfix no-top-space no-bottom-space"></div>
             </div>
         </div>
         <!-- END NOTIFICATIONS PORTLET-->
     </div>
     <div class="span6">
         <!-- BEGIN CHAT PORTLET-->
         <?php echo $this->partial('partial/panels/activity.phtml'); ?>
         <!-- END CHAT PORTLET-->
     </div>
 </div>