<?php
$this->headLink()
    ->appendStylesheet('/assets/bootstrap-toggle-buttons/static/stylesheets/bootstrap-toggle-buttons.css')
    ->appendStylesheet('/assets/uniform/css/uniform.default.css');

$this->inlineScript()
    ->appendFile('/assets/bootstrap-toggle-buttons/static/js/jquery.toggle.buttons.js')
    ->appendFile('/js/forms/product/setup.js');


?><div class="row-fluid">
    <div class="span12">
    <!-- BEGIN EXAMPLE TABLE widget-->
        <div class="widget blue">
            <div class="widget-title">
                <h4><i class="icon-cog"></i> Product Setup</h4>
                    <span class="tools">
                        <a href="javascript:;" class="icon-chevron-down"></a>
                    </span>
            </div>
            <div class="widget-body relative">
                <div id="productAddLoader" class="loader"></div>
                <?php echo $this->form()->openTag($form); ?>
                <div class="control-group">
                    <label class="control-label">Brand</label>
                    <div class="controls">
                        <?php echo $this->formElement($form->get('brand'));  ?>
                    </div>
                </div> 
                <div class="control-group">
                    <label class="control-label">Build</label>
                    <div class="controls">
                        <?php echo $this->formElement($form->get('build'));  ?>
                    </div>
                </div> 
                <div class="control-group">
                    <label class="control-label">Type</label>
                    <div class="controls">
                        <?php echo $this->formElement($form->get('type'));  ?>
                    </div>
                </div> 
                <div class="control-group">
                    <label class="control-label">Model</label>
                    <div class="controls">
                        <?php echo $this->formElement($form->get('model'));  ?>
                    </div>
                </div> 
                <div class="control-group">
                    <label class="control-label">Description</label>
                    <div class="controls">
                        <?php echo $this->formElement($form->get('description'));  ?>
                    </div>
                </div> 
                <div class="control-group">
                    <label class="control-label">Cost</label>
                    <div class="controls">
                        <div class="input-prepend input-append">
                            <span class="add-on">&#163;</span>
                            <?php echo $this->formElement($form->get('cpu'));  ?>
                            <span class="add-on">per unit</span>
                        </div>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">Price</label>
                    <div class="controls">
                        <div class="input-prepend input-append">
                            <span class="add-on">&#163;</span>
                            <?php echo $this->formElement($form->get('ppu'));  ?>
                            <span class="add-on">per unit</span>
                        </div>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">IBP</label>
                    <div class="controls">
                        <div class="input-prepend input-append">
                            <span class="add-on">&#163;</span>
                            <?php echo $this->formElement($form->get('ibppu'));  ?>
                            <span class="add-on">per unit</span>
                        </div>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">Trial Price</label>
                    <div class="controls">
                        <div class="input-prepend input-append">
                            <span class="add-on">&#163;</span>
                            <?php echo $this->formElement($form->get('ppuTrial'));  ?>
                            <span class="add-on">per unit</span>
                        </div>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">Power</label>
                    <div class="controls">
                        <div class="input-append">
                            <?php echo $this->formElement($form->get('pwr'));  ?>
                            <span class="add-on">watts</span>
                        </div>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">Active</label>
                    <div class="controls">
                        <div id="active-toggle-button">
                            <?php echo $this->formElement($form->get('active'));  ?>
                        </div>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">ECA Compatible</label>
                    <div class="controls">
                        <div id="eca-toggle-button">
                            <?php echo $this->formElement($form->get('eca'));  ?>
                        </div>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">MCD Compatible</label>
                    <div class="controls">
                        <div id="mcd-toggle-button">
                            <?php echo $this->formElement($form->get('mcd'));  ?>
                        </div>
                    </div>
                </div>
                <div id="productMsgs"></div>
                <?php echo $this->form()->closeTag($form); ?>
                <div class="clearfix">
                    <div class="btn-group pull-right">
                    <?php if ($this->isGranted('product.write')) { ?>
                        <button id="btn-product-modify" class="btn btn-success">
                            <i class="icon-ok"></i>&nbsp;Save Changes
                        </button>
                    <?php } ?>    
                    </div>
                </div>
            </div>
        </div>
    <!-- END EXAMPLE TABLE widget-->
    </div>
</div>