<?php 
$this->headLink()
    ->appendStylesheet('/assets/bootstrap/css/bootstrap-fileupload.css')
    ->appendStylesheet('/assets/uniform/css/uniform.default.css')
    ->appendStylesheet('/assets/data-tables/DT_bootstrap.css');


$this->inlineScript()
    ->appendFile('/js/jquery.blockui.js')
    ->appendFile('/assets/uniform/jquery.uniform.min.js')
    ->appendFile('/assets/data-tables/jquery.dataTables.js')
    ->appendFile('/assets/data-tables/DT_bootstrap.js')
    ->appendFile('/js/dynamic-table/legacy.js');

$this->headStyle()->captureStart() 
?>
    #legacy_tbl tbody td{
        vertical-align: middle;
    }
<?php 
$this->headStyle()->captureEnd();
?>
<div class="row-fluid">
    <div class="span12">
    <!-- BEGIN EXAMPLE TABLE widget-->
        <div class="widget red">
            <div class="widget-title">
                <h4><i class="icon-2x"></i>Legacy Product Catalog</h4>
                    <span class="tools">
                        <a href="javascript:;" class="icon-chevron-down"></a>
                    </span>
            </div>
            <div class="widget-body">
                <table class="table table-striped table-bordered table-hover" id="legacy_tbl">
                    <thead>
                    <tr>
                        <th>Description</th>
                        <th style="width: 120px">Type</th>
                        <th style="width: 60px" >Power</th>
                        <th style="width: 120px">Created</th>
                        <th style="width: 35px;">&nbsp;</th>
                    </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
    <!-- END EXAMPLE TABLE widget-->
    </div>
</div>
