<h1>I am in AuthDoctrine IndexController index action index.phtml</h1>

<?php echo $this->message; ?>

<hr />
<table>
	<tr>
		<th>getUsername</th>
		<th>getPassword</th>
		<th>getEmail</th>
		<th>getUserId</th>
		<th>getSecretQuestion</th>
	</tr>
<?php foreach ($users as $user) { ?>
	<tr>
		<td><?php echo $this->escapeHtml($user->getUsername());?></td>
		<td><?php echo $this->escapeHtml($user->getPassword());?></td>
		<td><?php echo $this->escapeHtml($user->getEmail());?></td>
		<td><?php echo $this->escapeHtml($user->getUserId());?></td>
		<td><?php echo $this->escapeHtml($user->getSecretQuestion());?></td>
	</tr>
<?php } ?>
</table>