<?php
$this->headLink()
    ->appendStylesheet('/assets/bootstrap-toggle-buttons/static/stylesheets/bootstrap-toggle-buttons.css')
    ->appendStylesheet('/assets/chosen-bootstrap/chosen/chosen.css')
    ;

$this->inlineScript()
    ->appendFile('/assets/bootstrap-wizard/jquery.bootstrap.wizard.min.js')
    ->appendFile('/assets/bootstrap-toggle-buttons/static/js/jquery.toggle.buttons.js')
    ->appendFile('/assets/chosen-bootstrap/chosen/chosen.jquery.min.js')
    ->appendFile('/js/forms/project/addtrial.js');

?>
<?php echo $this->form()->openTag($form); ?>
<div id="myModal3" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel3" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel3">Trial Created Successfully</h3>
    </div>
    <div class="modal-body">
        <p>The trial has been successfully created.<br>Would you like to go to the dashboard for the newly created trial?</p>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true"><i class="icon-remove"></i> No</button>
        <button id="btn-project-dashboard" class="btn btn-primary"><i class="icon-ok"></i> Yes</button>
    </div>
</div>
<div class="row-fluid">
    <div class="span12">
        
        <div id="msgs"></div>
        <div class="widget box green relative">
            <div id="setupLoader" class="loader"></div>
            <div class="widget-title">
                <h4>
                    <i class="icon-plus-sign-alt"></i> Create Trial
                </h4>
           <span class="tools">
              <a href="javascript:;" class="icon-remove" id="cancel-buildingadd"></a>
           </span>
            </div>
            <div class="widget-body">
                   <div id="pills" >
                    <ul>
                        <li><a href="#pills-tab1" data-toggle="tab">Step 1</a></li>
                        <li><a href="#pills-tab2" data-toggle="tab">Step 2</a></li>
                        <li><a href="#pills-tab3" data-toggle="tab">Step 3</a></li>
                        <li><a href="#pills-tab4" data-toggle="tab">Finish</a></li>
                    </ul>
                    <div class="progress progress-success progress-striped active">
                        <div class="bar"></div>
                    </div>
                    <div class="tab-content">
                        <div class="tab-pane" id="pills-tab1">
                            <h3>Step 1 - Details</h3>
                            <div class="control-group">
                                <label class="control-label">Name</label>
                                <div class="controls">
                                    <?php echo $this->formElement($form->get('name'));  ?>
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label">Mode</label>
                                <div class="controls">
                                    <div id="text-toggle-button">
                                        <?php echo $this->formElement($form->get('test'));  ?>
                                    </div>
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label">Contacts</label>
                                <div class="controls">
                                    <?php echo $this->formElement($form->get('contacts'));  ?>
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label">Sector</label>
                                <div class="controls">
                                    <?php echo $this->formElement($form->get('sector'));  ?>
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label">Build</label>
                                <div class="controls">
                                    <?php echo $this->formElement($form->get('retrofit'));  ?>
                                </div>
                            </div>
                            
                        </div>
                        <div class="tab-pane" id="pills-tab2">
                            <h3>Step 2 - Metrics</h3>

                            <div class="control-group">
                                <label class="control-label">Carbon Factor</label>
                                <div class="controls">
                                    <?php echo $this->formElement($form->get('co2'));  ?>
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label">Fuel Tariff</label>
                                <div class="controls">
                                    <div class="input-prepend input-append">
                                    <?php echo $this->formElement($form->get('fuelTariff'));  ?><span class="add-on">pence per unit</span>
                                    </div>
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label">RPI</label>
                                <div class="controls">
                                    <?php echo $this->formElement($form->get('rpi'));  ?>
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label">EPI</label>
                                <div class="controls">
                                    <?php echo $this->formElement($form->get('epi'));  ?>
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label">Maintenance</label>
                                <div class="controls">
                                    <div class="input-prepend">
                                    <span class="add-on">&#163;</span><?php echo $this->formElement($form->get('maintenance'));  ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane" id="pills-tab3">
                            <h3>Step 3 - Notes</h3>
                            <div class="control-group">
                                <label>Enter any additional information regarding the trial:</label>
                            </div>
                            <div id="notes">
                                <div class="control-group">
                                        <input type="text" class="span6 " name="note[]" placeholder="Addtional Note #1"/>
                                </div>
                                <div class="control-group">
                                        <input type="text" class="span6 " name="note[]" placeholder="Addtional Note #2"/>
                                </div>
                                <div class="control-group">
                                        <input type="text" class="span6 " name="note[]" placeholder="Addtional Note #3"/>
                                </div>
                            </div>
                            <div id="new-note">
                                <a class="btn btn-primary"><i class="icon-plus"></i> Add Note</a>
                            </div>
                        </div>
                        <div class="tab-pane" id="pills-tab4">
                            <h3>Step 4 - Confirmation</h3>
                            <div class="control-group">
                                <label>When you are satisfied with the setup of the trial click on the Create Trial button:</label>
                            </div>
                            <div class="control-group">
                                <label class="control-label">Name:</label>
                                <div class="controls">
                                    <span class="text" id="confirm-name">-</span>
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label">Details:</label>
                                <div class="controls">
                                    <span class="text" id="confirm-details">-</span>
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label">Build:</label>
                                <div class="controls">
                                    <span class="text" id="confirm-build">-</span>
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label">Additional Notes:</label>
                                <div class="controls">
                                    <span class="text" id="confirm-notes">-</span>
                                </div>
                            </div>
                        </div>
                        
                        <ul class="pager wizard">
                            <li class="previous first"><a href="javascript:;">First</a></li>
                            <li class="previous"><a href="javascript:;">Previous</a></li>
                            <li class="next last"><a href="javascript:;">Last</a></li>
                            <li class="next"><a  href="javascript:;">Next</a></li>
                            <li class="next finish" style="display:none;"><a href="javascript:;">Create Trial</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php echo $this->form()->closeTag($form); ?>
