<?php
?>
<div >
    <ul class="nav nav-pills">
        <li class="<?php echo ($navRoute=='model')?'active':''; ?>"><a href="/client-<?php echo $project->getClient()->getClientId(); ?>/project-<?php echo $project->getProjectId(); ?>/model/">System Costings Model</a></li>
        <li class="<?php echo ($navRoute=='forecast')?'active':''; ?>"><a href="/client-<?php echo $project->getClient()->getClientId(); ?>/project-<?php echo $project->getProjectId(); ?>/forecast/">Payback Forecast Model</a></li>
        <li class="<?php echo ($navRoute=='breakdown')?'active':''; ?>"><a href="/client-<?php echo $project->getClient()->getClientId(); ?>/project-<?php echo $project->getProjectId(); ?>/breakdown/">Space Breakdown</a></li>
        <li class="dropdown">
            <a href="#" data-toggle="dropdown" role="button" id="drop6" class="dropdown-toggle">Documents <b class="caret"></b></a>
            <ul aria-labelledby="drop5" role="menu" class="dropdown-menu" id="menu3">
                <li role="presentation"><a href="#" tabindex="-1" role="menuitem">Forecast (PDF)</a></li>
                <li role="presentation"><a href="#" tabindex="-1" role="menuitem">System Model (Excel)</a></li>
                <li class="divider" role="presentation"></li>
                <li role="presentation"><a href="#" tabindex="-1" role="menuitem">Quote (Style A)</a></li>
                <li role="presentation"><a href="#" tabindex="-1" role="menuitem">Quote (Style B)</a></li>
            </ul>
        </li>
    </ul>
</div>
