<div class="row-fluid">
    <div class="span12">
        <!-- BEGIN ORDERED LISTS PORTLET-->
        <div class="widget orange">
            <div class="widget-title">
                <h4><i class="icon-<?php echo $report->getGroup()->getIcon(); ?>"></i> <?php echo $report->getName(); ?> Report</h4>
                <span class="tools">
                <a href="javascript:;" class="icon-chevron-down"></a>
                <a href="javascript:;" class="icon-remove"></a>
                </span>
            </div>
            <div class="widget-body relative">
                <div id="reportLoader" class="loader"></div>
                <h4><?php echo $report->getName(); ?> Report</h4>
                <h5><?php echo $report->getDescription(); ?></h5>
                <!-- BEGIN REPORT PARTIAL-->
                <?php echo $this->partial('partial/report/'.$partialScript.'.phtml'); ?>
                <!-- END  REPORT PARTIAL-->
            </div>
        </div>
        <!-- END ORDERED LISTS PORTLET-->

    </div>
</div>